### PR TITLE
Remove deploy_linux.sh since no longer in use

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
The deploy_linux.sh file has not been in use since we moved over to debian building. Users who still use the source can use git or manually execute make dist.

**Context: Fixes an issue?**
Related to: https://github.com/jamulussoftware/jamulus/pull/2510#discussion_r826367788

**Does this change need documentation? What needs to be documented and how?**
CHANGELOG: Removed linux/deploy_linux.sh file since we provide compiled `.deb` files for installation on Debian based systems and no longer use this script. Linux users should download the source code from the GitHub repo via git, use the source from the GitHub release or run the commands directly via shell.

**Status of this Pull Request**
Ready to be merged

**What is missing until this pull request can be merged?**
Review

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Review by pljones — APPROVED** [review]
On the assumption this doesn't break the build....

**Review by hoffie — APPROVED** [review]
Yep, please wait for CI green before merge. :)

**Comment by ann0see** [comment]
I doubt it changes anything.

**Comment by ann0see** [comment]
Merging. It’s just a code ql hiccup again.

**Comment by ann0see** [comment]
@pljones I shortened the changelog entry. Can you put this into the release note?

**Comment by pljones** [comment]
I'll go with the even shorter version I used.  The ChangeLog shouldn't provide directions to people on how to deal with the change.  That should be provided in the current documentation.

**Comment by ann0see** [comment]
Then maybe at least add that we no longer use the script

**Pull request merged**
