### PR TITLE
tools/get_release_contributors: Improve Weblate compatibility (lookup by email, merge commit support)

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**
- tools/get_release_contributors: Ignore dependabot and weblate users
  Related: #2904

- tools/get_release_contributors: Add user lookup by email
  This extends the release contributor scripts to look up users by email via Github search/users API.
  This is helpful for the Weblate process which only adds the original authors as Co-authored-by.

  In addition, the output changes to fall back to realnames (from the Co-authored-by lines) if not Github login is found.
  To make that mixed output more readable, commas are added between user names now.

- tools/get_release_contributors: Avoid losing merge commit info
  Weblate places some authorship information in merge commits only.
  This commit ensures that merge commits are considered as well.

- tools/get_release_contributors: Improve logging

```
$ ./tools/get_release_contributors.py -q --from r3_9_0 --to r3_9_1rc1 --repo . 
Code contributors: @ann0see, @henkdegroot, @hoffie, @pljones, @softins
Application translators: @ann0see, @henkdegroot, @ignotus666, @mansil, @pljones, @trebmuh, J. Lavoie, 이정희
```

(Note: Stderr might now include more output, therefore redirection is helpful to get copy-pastable output)

CHANGELOG: SKIP

**Context: Fixes an issue?**
No (see Discord/Matrix discussion though)

**Does this change need documentation? What needs to be documented and how?**
No

**Status of this Pull Request**
Ready

**What is missing until this pull request can be merged?**
Reviews

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

cc @ignotus666

### CODE REVIEW

**Review by pljones — APPROVED** [review]

**Comment by hoffie** [comment]
PR updated with further improvements to capture co-authorship information from merge commits as well (as Weblate uses them).

**Review by ann0see — APPROVED** [review]
Didn't test it on my side, but I think it's ok.

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
Changelog IGNORE should be Changelog SKIP 😀

**Comment by hoffie** [comment]
> Changelog IGNORE should be Changelog SKIP 😀

Thanks, fixed. Too many days without a PR, it seems...

**Pull request merged**
