### PR TITLE
contribute Jamulus(1) manpage from Debian

### PR DESCRIPTION
**Pull request by mirabilos**
**Short description of changes**

Contribute the [Jamulus(1)](https://manpages.debian.org/bullseye/jamulus/Jamulus.1.en.html) manpage from Debian, in its current version (updated today for 3.8.1 and quickly rechecked against git master)

**Context: Fixes an issue?**

Debian likes to contribute its changes upstream.

**Does this change need documentation? What needs to be documented and how?**

Changes to `src/main.cpp` need to be reflected in the manpage appropriately. I’ll be available for formatting help if needed, but the burden to keep the manpage up-to-date wrt. the source code should lie with the source code change contributor.

**Status of this Pull Request**

Prod implementation, except I didn’t test the `Jamulus.pro` part to install it.

**What is missing until this pull request can be merged?**

Check whether I did the installation part right and in the right place. The file should end up under `$PREFIX/share/man/man1/` in most settings, `$PREFIX/man/man1/` in almost all remaining ones.

## Checklist
- [ ] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Great! Thank you. 

Fixes: https://github.com/jamulussoftware/jamuluswebsite/issues/321

Tagging @jamulussoftware/wikiadmin here since it’s related to the documentation. I think there are some open questions – especially how to keep the man page in sync.

**Comment by ann0see** [comment]
@ycollet you asked for a man page for Jamulus last year. Maybe you can comment on this PR and join the discussion?

**Comment by ycollet** [comment]
The man page looks OK for me.
For the sync of the page, maybe you can first accept and merge this commit and once in a while, a new pull request can be made to update this page.

**Comment by gilgongo** [comment]
Looking at the content and layout, **might** this be automatable from the content we already maintain for the website (the includes we use [like this](https://github.com/jamulussoftware/jamuluswebsite/blob/next-release/wiki/en/Include-Client-Commands.md) for example)? At least, this and `jamulus -h` should ideally be automatically paired in some way - or is that what's happening here?

If some form of automation is feasible, then I think we should investigate it at least. Otherwise, having two (or three?) places to maintain the information in this man page would seem a fairly large overhead given the small audience for it. We also can't expect the translations to be kept up to date with every release either BTW.

**Comment by mirabilos** [comment]
Jonathan dixit:

>Looking at the content and layout, **might** this be automatable from
>the content we already maintain for the website (the includes we use
>[like
>this](https://github.com/jamulussoftware/jamuluswebsite/blob/next-release/wiki/en/Include-Client-Commands.md)
>for example)? At least, this and `jamulus -h` should ideally be
>automatically paired in some way - or is that what's happening here?

It’s paired-ish, but a manpage has a different sorting order (first
the short options, alphabetically but uppercase before the corresponding
lowercase letter, then the long-only options), and I think the code does
not clearly distinguish between common, client-only, server-only and
directoryserver-only. The descriptions may also be a bit longer than in
a typical help output (or, at least, they SHOULD be), and I tend to
slightly reword them to minimise hyphenation on a standard $MANWIDTH.

I’ve done the work to extract the relevant information twice now, and
I urge against trying to automate this.

>investigate it at least.

Perhaps. But maybe first merge this?

>overhead given the small audience for it. We also can't expect the

Small overhead, as in, all Unix (GNU/Linux, BSD, etc.) and possibly
some Macintosh users?

>translations to be kept up to date with every release either BTW.

Yeah, manpage translations are… not very much a thing. I’d not
tackle this unless someone actually volunteers. People who read
manpages tend to read (even prefer) the English versions anyway.

I’d point nōn-English-speaking users towards the colourful website.

bye,
//mirabilos
-- 
> Hi, does anyone sell openbsd stickers by themselves and not packaged
> with other products?
No, the only way I've seen them sold is for $40 with a free OpenBSD CD.
	-- Haroon Khalid and Steve Shockley in gmane.os.openbsd.misc

**Comment by gilgongo** [comment]
Just to be clear: are you also volunteering to keep this man page up to date @mirabilos?

**Comment by mirabilos** [comment]
Jonathan dixit:

>Just to be clear: are you also volunteering to keep this man page up to date @mirabilos? 

I wrote something about that above. Was that unclear?

bye,
//mirabilos
-- 
„Cool, /usr/share/doc/mksh/examples/uhr.gz ist ja ein Grund,
mksh auf jedem System zu installieren.“
	-- XTaran auf der OpenRheinRuhr, ganz begeistert
(EN: “[…]uhr.gz is a reason to install mksh on every system.”)

**Comment by gilgongo** [comment]
Apologies, I missed that. You can help with formatting but we need to maintain it. 

And sorry for another stupid question: you say the context here is that "Debian likes to contribute its changes upstream." Does this mean the "change" is that man page already exists in the Debian package?

**Comment by mirabilos** [comment]
Jonathan dixit:

>"change" is that man page already exists in the Debian package?

Yes, of course. Binaries without manpages violate Debian policy,
and to write a manpage for one that lacks one is even part of
the trials when one applies to become Debian Developer.

bye,
//mirabilos
-- 
  "Using Lynx is like wearing a really good pair of shades: cuts out
   the glare and harmful UV (ultra-vanity), and you feel so-o-o COOL."
                                         -- Henry Nelson, March 1999

**Comment by gilgongo** [comment]
Oh OK. Thanks for the clarification.

**Comment by gilgongo** [comment]
OK, so to return to the issue of maintaining this content: if we just need a man page to be compatible with Debian policy, how about we merge this as it is (as @mirabilos suggests, because I assume that would help in some way), then replace it with a version we can generate dynamically later: "#include <manpageheader>""Jamulus --help""#include <manpagefooter>" -- then refer to the online manual in the header and footer, plus licence details.  See `man cat`, for example?

**Comment by mirabilos** [comment]
Jonathan dixit:

>in some way), then replace it with a version we can generate
>dynamically later: "#include <manpageheader>""Jamulus --help""#include

I’d really prefer you don’t. Generated manpages are usually of
very bad quality (both formatting and content-wise).

And I’m still around to help if needed.

bye,
//mirabilos
-- 
15:39⎜«mika:#grml» mira|AO: "mit XFree86® wär’ das nicht passiert" - muhaha
15:48⎜<thkoehler:#grml> also warum machen die xorg Jungs eigentlich alles
kaputt? :)    15:49⎜<novoid:#grml> thkoehler: weil sie als Kinder nie den
gebauten Turm selber umschmeissen durften?	-- ~/.Xmodmap wonders…

**Comment by gilgongo** [comment]
I too would prefer to have a high quality bespoked man page. But you may be underestimating the impact of what you are asking us to do. Given our resources and release frequency, it isn't a good idea to have a _third_ area of semi-duplicated content to worry about, if only because it's likely to be benefit rather less than 5% of the audience. Jamulus is essentially a GUI application after all. If we must have a man page, I'd prefer to have an easily maintained one along the lines of [icecat](https://www.mankier.com/1/icecat) or [VLC](https://linux.die.net/man/1/vlc).

**Comment by mirabilos** [comment]
Jonathan dixit:

>Jamulus is essentially a GUI application after all. If we must have a
>man page, I'd prefer to have an easily maintained one along the lines
>of [icecat](https://www.mankier.com/1/icecat) or

It’s not much more than that currently, and in many cases you can
copy the help text to the option description (and add which modes
it applies to), but this makes it much more useful.

bye,
//mirabilos
-- 
Gestern Nacht ist mein IRC-Netzwerk explodiert. Ich hatte nicht damit
gerechnet, darum bin ich blutverschmiert… wer konnte ahnen, daß SIE so
reagier’n… gestern Nacht ist mein IRC-Netzwerk explodiert~~~
	(as of 2021-06-15 The MirOS Project temporarily reconvenes on OFTC)

**Comment by gilgongo** [comment]
I don't doubt the usefulness - it's the cost/benefit I have a problem with. But no matter - let's merge it for now. @pljones is working on some stuff that will facilitate being able to generate it dynamically later.

**Review by gilgongo — APPROVED** [review]
Not much of this follows https://jamulus.io/contribute/Style-and-Tone but I think we can let that pass for now until we do this as as discussed.

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
@gilgongo should we add updating the man page to the release checklist?

**Comment by gilgongo** [comment]
I guess so. Something like "Make sure any changes to jamulus -h are reflected in website Include-*.md and man page" perhaps?

**Comment by ann0see** [comment]
Yeah. And give a link to the relevant folder here.

**Pull request merged**
