### PR TITLE
Pr957 server recording

### PR DESCRIPTION
**Pull request by dcorson-ticino-com**
Add one line in ClientDlg to remove formatting for recording when license refused.

### CODE REVIEW

**Comment by pljones** [comment]
It shouldn't need all this complexity.  It's all currently managed in UpdateTitle() and that's where the change should be done.

**Comment by ann0see** [comment]
Related to #1089

**Comment by pljones** [comment]
Is this superseded now, then?

**Comment by dcorson-ticino-com** [comment]
Yes, to be ignored

**Comment by pljones** [comment]
OK, can you close the PR, please :)

**Pull request closed without merging**
