### PR TITLE
Update pt_PT translation

### PR DESCRIPTION
**Pull request by Snayler**

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
Thank you very much for your work! Looks good to me.

- [x] Translator listed in the `src/util.cpp`https://github.com/jamulussoftware/jamulus/blob/466c76e3007c2a6ae5cef2a43669764cf7c1964b/src/util.cpp#L498
- [x] Punctuation and spacing consistent
- [x] Signal words consistent ("ASIO", "Buffer")
- [x] No untranslated strings (`grep unfinished -5 src/res/translation/translation_$TRANSLTION*.ts`)
- [x] Only a single `.ts` file checked in (+.qm which is known to be not a problem)

**Comment by Snayler** [comment]
>     * [x]  Only a single `.ts` file checked in (+.qm which is known to be not a problem)

So no need for the .qm file next file I do the translations?

**Comment by hoffie** [comment]
> So no need for the .qm file next file I do the translations?

As far as I understand: Yes, there's no need for you to check that in all required files will be generated as part of the release process. :)
It's no issue either though.

**Review by softins — APPROVED** [review]
Looks good to me. I couldn't find any conflicting accelerator keys.

**Pull request merged**
