### PR TITLE
unclear error message made precise

### PR DESCRIPTION
**Pull request by DavidSavinkoff**
**Short description of changes**

At line 1047, or nearby, in jamulus/master/src/main.cpp:
QString errmsg = "%1: '%2' needs a numeric argument between '%3' and '%4'.";
Should be rewritten in the Queen's English to be:
QString errmsg = "%1: '%2' needs a numeric argument from '%3' to '%4'.";
In order to be mathematically correct in English.
This fixes the meaning in all places where this message ocurrs.
**Context: Fixes an issue?**

**Does this change need documentation? What needs to be documented and how?**

**Status of this Pull Request**

**What is missing until this pull request can be merged?**

## Checklist

- [ ] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [ ] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Review by softins — APPROVED** [review]
Should do a squash merge

**Review by ann0see — APPROVED** [review]
Looks simple ;-). Thanks

**Comment by ann0see** [comment]
@DavidSavinkoff Could you please also give a proposal for the ChangeLog?

**Comment by DavidSavinkoff** [comment]
My proposals for the ChangeLog are:
1)Number range command line error messages reworded accurately.
2)Command line error messages from GetNumericArgument() of the form:
{variable} needs a numeric argument between {low value} and {high value}.
corrected to:
{variable} needs a numeric argument from {low value} to {high value}.

I think (1) is better.

**Comment by ann0see** [comment]
Yep, will use (1).

**Pull request merged**
