### PR TITLE
Build: Mac: Keep the signing-related keychain unlocked

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**
This fixes hanging Mac build runs in CI which got stuck as they required interactive unlocking of the keychain.
This issue only became appareant after the switch to universal builds as that made the build take longer than the re-lock interval.

CHANGELOG: Build: Mac: Keep the signing-related keychain unlocked

**Context: Fixes an issue?**
Fixes: #2925

**Does this change need documentation? What needs to be documented and how?**
No.

**Status of this Pull Request**
The fix has already been committed and tested successfully on @emlynmac's repo where I've manually modified the r3_9_1 tag to do so.

**What is missing until this pull request can be merged?**
Reviews.
(CI on this PR must not file, but it being successful does not prove anything either ;))

Please merge once reviews are completed.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

AUTOBUILD: Please build all targets

### CODE REVIEW

**Review by emlynmac — APPROVED** [review]
Nice; LGTM

**Comment by ann0see** [comment]
@daryu maybe you experienced something like this too? Could you please comment?

**Comment by pljones** [comment]
One other comment: why did the build _hang_ rather than fail?  Do we know?  Is that something that could have been prevented and made to fail with a useful error?

**Review by pljones — APPROVED** [review]
If it works, it works.  Subject to my other comment that's out of scope for this hot fix.

**Comment by hoffie** [comment]
> One other comment: why did the build _hang_ rather than fail? Do we know? Is that something that could have been prevented and made to fail with a useful error?

As far as I have found, it's likely not a real hang, but rather waiting for activity in a graphical dialog box, which we'll never see in the CI which is only CI-based.

**Comment by pljones** [comment]
> > One other comment: why did the build _hang_ rather than fail? Do we know? Is that something that could have been prevented and made to fail with a useful error?
> 
> As far as I have found, it's likely not a real hang, but rather waiting for activity in a graphical dialog box, which we'll never see in the CI which is only CI-based.

That's what I was guessing, too.  Is there any way to prevent it, or a tool that better understands automated CI?

**Comment by hoffie** [comment]
> That's what I was guessing, too. Is there any way to prevent it, or a tool that better understands automated CI?

I don't think so. The most official way seems to be Xcode, which is purely graphical. `codesign` is the fall back and is implicitly used by `macdeployqt`. It's probably not `codesign` itself who generates the dialog box, but rather the system keychain integration. I don't know of any other tool.
https://stackoverflow.com/questions/20205162/user-interaction-is-not-allowed-trying-to-sign-an-osx-app-using-codesign

**Comment by ann0see** [comment]
I remember suspecting something like that some time ago too. That was the Apple script invocation in create-dmg (GitHub fixed it on their side a while ago.)

**Review by ann0see — APPROVED** [review]

**Comment by pljones** [comment]
I _think_ this actually didn't make the 3.9.1 cut.  This is just looking at the merges since the r3_9_1 tag.

**Pull request merged**
