### PR TITLE
Autobuild: Reduce Qt download size & bump aqtinstall to 2.0.6

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**

- Autobuild: Bump aqtinstall to 2.0.6

- Autobuild: Add proper quoting around aqt invocations

- Autobuild: Download required Qt archives only

- Autobuild: Shorten aqt install-qt invocation on Windows

CHANGELOG: Autobuild: Reduced Qt download size and updated aqtinstall to 2.0.6

**Context: Fixes an issue?**

- Saves some time (download/install now takes [11.2s](https://github.com/hoffie/jamulus/runs/5524565838?check_suite_focus=true#step:7:134) vs. [25.5s](https://github.com/jamulussoftware/jamulus/runs/5524335865?check_suite_focus=true#step:7:199)), bandwidth, storage and cache save/restore volume ([62MB](https://github.com/hoffie/jamulus/runs/5524565838?check_suite_focus=true#step:33:3) vs. [98MB](https://github.com/jamulussoftware/jamulus/runs/5524335865?check_suite_focus=true#step:33:3)).
- Decreases artifact size, most notably on Windows ([75.3MB](https://github.com/jamulussoftware/jamulus/actions/runs/1974596764) -> [61.8MB](https://github.com/hoffie/jamulus/actions/runs/1974707545)) -> Needs verification of correctness

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Ready.

**What is missing until this pull request can be merged?**

- [x] All builds green
- [x] Smoke test Windows (needs special consideration as artifacts are ~20% smaller, maybe due to bundling of less DLLs)
- [x] Smoke test Mac
- [x] Smoke test iOS

I believe that all possible errors which might be introduced by this change should either show up during build or during binary launch.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Anything specific to look for? Missing translations? Missing multi-threading support?

**Comment by ann0see** [comment]
Windows ASIO build works (audio).

**Review by ann0see — APPROVED** [review]
Unless macOS shows any errors (which I can't test at the moment since my VM doesn't start up) I think it's OK. Do we need more tests

**Comment by ann0see** [comment]
Also tested both macOS clients and they worked (audio via black hole)

**Comment by hoffie** [comment]
> Anything specific to look for? Missing translations? Missing multi-threading support?

Hmm, some missing modules cause failures (e.g. macextras), but other's don't (winextras, qttranslations):
https://github.com/hoffie/jamulus/actions/runs/1975744507

This PR essentially does what you did for Android here:
https://github.com/jamulussoftware/jamulus/pull/2394/files

(Except that we've never specified dependencies at all which made us download *everything*)

I'm not sure if or what for `winextras` is needed, but I'd rather keep it as part of this PR.
I suspect dropping `qttranslations` will drop support for Qt-provided translations for default items like "OK": https://github.com/qt/qttranslations/tree/dev/translations

It's hard to say what to look for. The still listed Qt archives are those which are not dropped (nothing to check as there's no change). The more interesting part is seeing whether any other archive might be needed and might fail silently.

At the same time, if it does break something, Android has probably been broken since #2394 anyway. ;)

This is the full list for Mac: `qt3d qtbase qtcanvas3d qtconnectivity qtdeclarative qtgamepad qtgraphicaleffects qtimageformats qtlocation qtmacextras qtmultimedia qtquickcontrols qtquickcontrols2 qtremoteobjects qtscxml qtsensors qtserialbus qtserialport qtspeech qtsvg qttools qttranslations qtwebchannel qtwebsockets qtwebview qtxmlpatterns`.

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
Interesting side fact: I can rename d3dcompiler_47.dll libEGL.dll libGLESv2.dll and Jamulus still starts without error.

**Comment by hoffie** [comment]
> Interesting side fact: I can rename d3dcompiler_47.dll libEGL.dll libGLESv2.dll and Jamulus still starts without error. To me this seems as if we can remove OpenGL on Windows.

What artifact did you use for this test -- this PR or very recent master?
I would have assumed that after this PR d3* would no longer be distributed?

**Comment by ann0see** [comment]
Good question. I'll retry with the current master.

**Comment by ann0see** [comment]
Yes, the build from master still has these files.

**Comment by hoffie** [comment]
Hmm, I've no idea what adds them. When manually running the relevant `aqt` command, I don't see these added, but maybe I'm missing something.

**Pull request merged**
