### PR TITLE
Server tray icon update

### PR DESCRIPTION
**Pull request by henkdegroot**
**Short description of changes**

Server tray icon update

**Sample screenshots**
_Windows Inactive State:_
windows-inactive

_Windows Active State:_
windows-active

_macOS Inactive State:_
macOS-inactive

_macOS Active State:_
macOS-active

**Context: Fixes an issue?**

Fixes: #2112

**Does this change need documentation? What needs to be documented and how?**

The current documentation does not explain the two different states of the icon. It would be nice to have this included in the server manual.

**Status of this Pull Request**

Complete

**What is missing until this pull request can be merged?**

Nothing

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Review by pljones — APPROVED** [review]

**Comment by pljones** [comment]
@gilgongo as there are Server documentation changes being made, can this be picked up?  Or would you rather a separate change?

**Review by ann0see — APPROVED** [review]
Tested on Windows JACK version and it seems to be ok.

**Comment by gilgongo** [comment]
I guess I can put it into the server docs change as a new section that says what the dot means, yes.

**Comment by gilgongo** [comment]
Reminder to self: pull this into the separate update for 3.8.2

**Pull request merged**
