### PR TITLE
Update Opus to v1.4

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

Updates Opus to the latest version. Local testing on Linux was ok.

CHANGELOG: Updated Opus to v1.4

**Context: Fixes an issue?**

Should fix some compiler warnings. 

Fixes: #2817

**Does this change need documentation? What needs to be documented and how?**

No

**Status of this Pull Request**

Needs testing on Windows

**What is missing until this pull request can be merged?**

Review and test on non Linux OS

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Just wanted to link https://github.com/xiph/opus/issues/241 as this will introduce opus as submodule.

**Comment by ann0see** [comment]
@pljones would you add this to the next release or should we wait?

**Comment by pljones** [comment]
I'll pull the Windows assets and test it - if it's okay I think we should go ahead.

**Comment by pljones** [comment]
Opens and runs.  I got one settings glitch (Qt6-related, I think) - "My Profile" tab didn't appear first time I ran.  Couldn't reproduce the glitch, though.

I'll be trying it out for audio tomorrow.

**Comment by ann0see** [comment]
Done. I've also experienced this bug. Qt6 feels buggy.

**Comment by ann0see** [comment]
@pljones I hope this now works.

**Comment by pljones** [comment]
> @pljones I hope this now works.

Yep, Qt6.5.2 and "My Profile" tab appears on clicking the "Settings" checkbox.

**Review by pljones — APPROVED** [review]

**Pull request merged**
