### PR TITLE
NSIS: Increase height of ASIO driver explanation label

### PR DESCRIPTION
**Pull request by SeeLook**
- also move down button under the label apparently

But wait for artifacts - I will check the installer then, take a picture...
Then we will see is it worthy of something.

### CODE REVIEW

**Comment by ann0see** [comment]
Just stopped the CI since it took too long

**Comment by ann0see** [comment]
@SeeLook you can now take a picture

**Comment by ann0see** [comment]
For me it doesn't seem as if it fixed this issue.

**Comment by SeeLook** [comment]
Jamulus-installer-en
Jaumulus-installer

Total failure....
But checking installer by artifacts of pull request is wild-goose chase,
so please take this burden out of my head.
As I said, I don't have build environment for Windows and it is not that easy to get one for me.

**Comment by ann0see** [comment]
Ok. I'll look into it ;-).

**Pull request closed without merging**
