### PR TITLE
Make connect dialog show up as fullscreen on iOS

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

Makes Connect dialog show up in full screen like Android if Qt6 is used. This fixes a severe UI issue on the Qt6 build of Jamulus for iOS which didn't allow to even tap the connect button. Now the connect dialog looks like this in dark mode: (broken styling but usable)
Fixed Connect Dialog iOS

CHANGELOG: iOS: Fixed GUI issue preventing the connect dialog to show correctly

**Context: Fixes an issue?**

Related to issues mentioned in https://github.com/jamulussoftware/jamulus/issues/2711

**Does this change need documentation? What needs to be documented and how?**

No
**Status of this Pull Request**
Works based on local build. Didn't test IPA built by GitHub - but this still uses Qt5

**What is missing until this pull request can be merged?**

Nothing
## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
The chat dialog probably also needs this.

**Comment by softins** [comment]
Looks like the Connect Dialog list entries also need some work to be compatible with a dark mode theme. I suspect those texts are set specifically to black instead of being left to default.

**Comment by ann0see** [comment]
@pljones Probably you can't test this. A review would still be good.

**Comment by pljones** [comment]
Might be the weekend before I can test it but it looks like it shouldn't cause problems.

**Comment by ann0see** [comment]
BlissOS Android test is ok.

**Comment by pljones** [comment]
OK, that appears to work for me (moto g(9) power,  Android 11)
ConnectDialogFullScreen

**Pull request merged**
