### PR TITLE
Drop admin rights on open Jamulus after install

### LINKED ISSUE #860: Remember if user opened Jamulus on last install/skipped ASIO warning
From: #841 
The new windows installer currently only remembers if the user checked "Install desktop icon". Should we also save if the user checked the checkbox to open Jamulus or skipped the ASIO warning?

### LINKED ISSUE #995: Do not automatically open Jamulus after install with new installer
**Is your feature request related to a problem? Please describe.**
Once a new user without admin privileges installs Jamulus and the installer opens the app, it might run as administrator and therefore not as the person who is currently logged in. This means that the user might think that settings are not saved once he re-opens Jamulus with his user privileges. 
**Describe the solution you'd like**
I suggest not to automatically open Jamulus after the installer ran, although it might be a bit more inconvinient for the user. It would not cause confusion.

**Describe alternatives you've considered**

--

**Additional context**

--

### PR DESCRIPTION
**Pull request by ann0see**
Fixes #995 with a workaround explained here: http://mdb-blog.blogspot.com/2013/01/nsis-lunch-program-as-user-from-uac.html
Fixes #860 (not the ASIO part, but that's probably a wontfix).

### CODE REVIEW

**Comment by ann0see** [comment]
Sorry softins, I don't know why it automatically assigned you here. Probably the setting is still not 100% correct.

**Review by pljones — APPROVED** [review]
I'm going to assume you've tested all the scenarios for saving state.  I've forgotten my NSIS syntax...

**Comment by ann0see** [comment]
Yes, it’s almost the same code as the other checkbox and I did check it. If bugs occur, sure, we can solve them.

**Review by softins — APPROVED** [review]
OK, I haven't the ability to test this, but it looks sensible, and I have read the original description of the technique.

**Comment by ann0see** [comment]
It’s probably not the cleanest way to solve it, but it seems to work. I‘ll merge this now.

**Pull request merged**
