### PR TITLE
Autobuild: Minimize JSON-RPC workflow permissions

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Removes any permissions from JSON-RPC check. We might even drop the secret in the env fully.

It fails as expected if there is a change to the function documentation:
https://github.com/ann0see/jamulus/actions/runs/3505130530

Other change doesn't make the check fail: https://github.com/ann0see/jamulus/actions/runs/3505127551

CHANGELOG: SKIP
**Context: Fixes an issue?**
No. But related to #1737 

**Does this change need documentation? What needs to be documented and how?**

No

**Status of this Pull Request**
Review by @hoffie 

**What is missing until this pull request can be merged?**
Theoretical review. I might not have thought about all possible cases where this check should be run.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
Looks good to me.

> We might even drop the secret in the env fully.

Worth a try. ;)

**Comment by ann0see** [comment]
Ok. Removing the token works:

Successful run without changes: https://github.com/ann0see/jamulus/actions/runs/3777431973/jobs/6421260779
Failed run with changes: https://github.com/ann0see/jamulus/actions/runs/3777433469

**Comment by ann0see** [comment]
I think after this is merged, we can remove even more permissions in GH settings.

**Review by pljones — APPROVED** [review]
Build is clean -> good.

**Pull request merged**
