### PR TITLE
feature request #141: add server binding address

### PR DESCRIPTION
**Pull request by buv**
Tying a specific IP address to a jamulus server on a host with multiple IP addresses I find very useful. So I added a command line argument --serverbindip (followed by the IP address to bind to) and routed it through until it reaches socket.cpp.

Since I am not a C++ programmer, any feedback is welcome.

### CODE REVIEW

**Comment by gilgongo** [comment]
Hi - thanks for this! I've linked this PR to a prior discussion in which one method was discussed to do this but I'm not sure what happened in the end.

**Review by pljones — APPROVED** [review]

**Review by softins — APPROVED** [review]
Nicely done - thank you! I've built and tested, and all seems ok.

**Review by softins — CHANGES_REQUESTED** [review]
There is a Windows build issue that needs to be resolved before this can be merged. `arpa/inet.h` is not available under Windows.

**Comment by softins** [comment]
@buv `arpa/inet.h` is not available under Windows. Please could you remove that `#include` and instead of using `inet_addr()`, revise your address binding in `CSocket::Init()` to use the same technique as is used in `CSocket::SendPacket()` to set the destination address when sending? Thank you!

**Review by pljones — CHANGES_REQUESTED** [review]
As per @softins comment.

**Comment by buv** [comment]
Changes are made.

**Review by softins — APPROVED** [review]
That's great, thank you!

**Review by pljones — APPROVED** [review]

**Comment by pljones** [comment]
Thanks for the change!

**Comment by gilgongo** [comment]
Just a minor thing, but seeing as this option doesn't have a short form, would it be too late to drop the "server" bit from it? We don't use (for example) `--serverlog` or `--serverdelaypan` for example, and just have it as `--bindip`. Just makes things a bit more compact on the CLI is all.

**Comment by pljones** [comment]
`--serverpublicip` is there already.  Arguably, so is `--centralserver` :)...

**Comment by gilgongo** [comment]
Oh OK. Well never mind then.

**Comment by buv** [comment]
I tried to "orient" (euphemism for copy-and-paste) myself on the --serverpublicip parameter and did not want to pertubate the shortcut name space. "Shortcuts for all" is perhaps then another feature request? ;-)

**Comment by hoffie** [comment]
@buv Do you want to add yourself to the contributors list?
https://github.com/jamulussoftware/jamulus/blob/0d593fc959a7bdca351d27fe10d59e775cc6228c/src/util.cpp#L492

This would have to be a separate PR as this one has already been merged.

**Comment by buv** [comment]
Thank you very much for the invitation!

**Pull request merged**
