### PR TITLE
Add feature request template

### PR DESCRIPTION
**Pull request by ann0see**
Same as #924

### CODE REVIEW

**Review by gilgongo — APPROVED** [review]

**Comment by pljones** [comment]
Hm.

I think the template should have a guidance section (with "remove this before submitting", of course) that explains what is likely to be _considered_, let alone accepted.

That is - Jamulus does what Jamulus does.  It avoids doing what other software does deliberately to avoid both processing overhead and maintenance overhead.  So if there is another way to solve the problem, that's likely a better solution.

**Comment by ann0see** [comment]
What about:

"Thanks for opening a new feature request! Please keep in mind that Jamulus achieves low latency audio by reducing complexity and following the "Keep it simple and stupid" approach. Adding new features may result in more processing and maintenance overhead so please be sure that your feature can not be achieved by different approaches/software too."

**Comment by pljones** [comment]
Yep, that's the idea.  Maybe add "Make it clear why here." on the end.

**Comment by ann0see** [comment]
I wouldn't stress it too much since it might sound intimidating. 

If we go too far it could sound like:

Thanks for your feature request and all the work you put into thinking about it. Since we don't like to introduce too many new features, you can be quite sure that it will not be implemented.

**Comment by ann0see** [comment]
I've now added your suggestion, but my comment is stil valid ;-).

**Comment by pljones** [comment]
Looks better now :)

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
Great! merged now.

**Pull request merged**
