### PR TITLE
Autobuild: Fix iOS artifact name

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**

The file is currently named *Unsigned1.ipa. The 1 doesn't belong there and has wrongfully been added as part of the refactoring in f460f5ce276d8907e0784e7993c9532b72daa30f.

Note: As this is a trivial fix I'll likely merge this as soon as there's a single approval.

CHANGELOG: (No extra mention; list it with the iOS refactoring PR #2521)

**Context: Fixes an issue?**

No Github Issue.

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Ready on CI green.

**What is missing until this pull request can be merged?**

CI/Reviews.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [ ] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Review by ann0see — APPROVED** [review]
Yeah. Noticed that too. Thanks for fixing

**Comment by ann0see** [comment]
ADMIN MERGED.

**Comment by ann0see** [comment]
I think this should be changelog skipped. Another idea would be changelog: condense #<issueID> which is taken up by the script

**Comment by pljones** [comment]
On the ChangeLog, I'd take the following approach:
* If this is _just_ a _trivial_ fix to an existing change, then either no extra entry.
* If this is a _non-trivial_ fix to an existing entry, then it needs listing (contributor and PR) with the existing change.
In this case, it's easiest to give the existing ChangeLog entry with "FIX" and a description _**appended**_.  The grouping should then group it with the existing entry and it can be manually merged as seen fit.

**Pull request merged**
