### PR TITLE
Mac: Use latest Xcode version with SDK 10.15 support

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**

This PR updates the autobuild configuration to use Xcode 12.1.1 (from 11.7). 12.1.1 is the latest release with SDK 10.15 included. SDK 10.15 is the highest release supported by Qt5, which is why we should not update to any higher version right now.

This official page confirms that 12.1.x is (and probably will stay?) the last version to support SDK 10.15, which we need for Qt5 compatibility: https://developer.apple.com/support/xcode/
This inofficial page lists 12.1.1 as the most-recent 12.1.x release: https://xcodereleases.com/

This is a continuation of #1794.

**Context: Fixes an issue?**

Nothing specific. The goal is to use the latest supported configuration.

**Does this change need documentation? What needs to be documented and how?**

No.
**Status of this Pull Request**

Ready.

**What is missing until this pull request can be merged?**

- [ ] Testing on Mac

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
@softins @emlynmac cound you please test this?

**Comment by ann0see** [comment]
Needs to be rebased.

**Comment by hoffie** [comment]
> Needs to be rebased.

Thanks for the pointer, done.

**Comment by ann0see** [comment]
I think the CI should be enough to verify it works? I have a VM on the latest version of macOS, so I assume I can only test the latest version of Xcode.

**Comment by hoffie** [comment]
I think the build artifact should be tested, mainly on rather old Mac versions.
I'm not sure if we should require explicit testing or if any testing in the 3.9.0 beta/rc phase should be enough (I tend to say so).

**Review by softins — APPROVED** [review]
Build log looks ok, and the artifact running on my Mac (Mojave) seems to run ok too.

**Review by ann0see — APPROVED** [review]
Since I'm quite sure the problem was my Qt6 try, I'll approve this

**Comment by softins** [comment]
> @softins did you also check your location in my profile is it still correct?

Sorry, I don't understand the question.

**Comment by ann0see** [comment]
Sorry if I was unclear: Did your profile information stay sane, i.e. are all your profile infos; especially the country value correctly copied from a previous install?

**Comment by ann0see** [comment]
Sorry. I Should have quoted "My profile".

**Comment by softins** [comment]
Yes, all looked fine, switching between this version, 3.8.2 and the one from #2421. No surprises.

**Comment by softins** [comment]
Ah, remember the ini file in the unsigned versions will be in a different place from the signed ones. But the unsigned ones will have found my old ini from a couple a versions ago, and it was still sane.

**Comment by ann0see** [comment]
Great. Thanks. So it was related to the Qt6 issue.

**Comment by softins** [comment]
Yes, most likely, as the country codes changed.

**Pull request merged**
