### PR TITLE
LED naming update in code

### PR DESCRIPTION
**Pull request by henkdegroot**
**Short description of changes**

LED image files and references update to match.

CHANGELOG: Internal: Rename LED resources

**Context: Fixes an issue?**

Fixes: #2365 

**Does this change need documentation? What needs to be documented and how?**

No

**Status of this Pull Request**

Complete

**What is missing until this pull request can be merged?**

Nothing

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by henkdegroot** [comment]
The LEDs are still the same, just the filenames have changed makes I guess makes it a bit difficult to see.

For instance, the "Big" version of the Round LED was named: CLEDBlackSmall.png and the "Small" version was named: LEDBlackSmall.png. Which is what was kind of confusing.
The new name for the CLEDBlackSmall.png is CLEDBlackBig.png and the new name for the LEDBlackSmall.png is CLEDBlackSmall.png.

Because the filename CLEDBlackSmall.png is the same as the previous "big" version, git shows it as if these are now smaller.
The CLEDBlackBig.png (new filename) is shown as added and the LEDBlackSmall.png is shown as deleted.

Hope this makes sense.

**Comment by ann0see** [comment]
Ok. Thanks.

**Review by ann0see — APPROVED** [review]
Tested and looks good.

**Review by hoffie — APPROVED** [review]
Thanks @henkdegroot and sorry for leaving this laying around for so long!
Naming seems good, styles still seem to work properly.

**Pull request merged**
