### PR TITLE
Upgrade create-dmg to latest version 1.1.0

### PR DESCRIPTION
**Pull request by ann0see**
I'd like to have this in 3.9.0

**Short description of changes**

Upgrades create-dmg to the latest version. Nothing changed (especially this PR does not change the compression format)

CHANGELOG: Mac: Upgrade create-dmg to the latest version

**Context: Fixes an issue?**

No. Related to: https://github.com/jamulussoftware/jamulus/issues/2663

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**
Ready for second review. 

**What is missing until this pull request can be merged?**

CI and testing

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [ ] I've filled all the content above

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
Looks good. [Proper create-dmg version has been installed](https://github.com/jamulussoftware/jamulus/runs/7010310743?check_suite_focus=true#step:9:1195), build is green. Can't do any other Mac tests though.

**Comment by ann0see** [comment]
I'll test it once the CI has compiled again.

**Comment by ann0see** [comment]
Ok. Tested the old build (with the wrong commit message) and it installs as before on macOS

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
@pljones Another minor fix here.

**Comment by pljones** [comment]
Where?

**Comment by ann0see** [comment]
Upgrade was changed to upgraded

**Comment by pljones** [comment]
Just to note: as I'm editing these _by hand_ (I'd have to delete them all and start again otherwise, losing all the edits I've already done), it's clearer to state the change you're suggesting than making it.

**Comment by ann0see** [comment]
Ok. Will do that in future.

**Pull request merged**
