### PR TITLE
Refactoring: Remove "Jamulus" from translated texts

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Removes found occurances of "Jamulus" throughout the code.
We will read the app name from the APP_NAME constant now.

CHANGELOG: Refactoring: Removed occurrences of plain name "Jamulus" in translatable texts.

**Context: Fixes an issue?**

Fixes: https://github.com/jamulussoftware/jamulus/issues/2354

**Does this change need documentation? What needs to be documented and how?**

No. 

**Status of this Pull Request**

Ready for review.

**What is missing until this pull request can be merged?**

Nothing.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want (compilation seems to be fine according to the CI, same for the most visible messages on Windows)
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
@hoffie @gilgongo could you please review?

**Review by hoffie — APPROVED** [review]

**Comment by hoffie** [comment]
Not entirely sure if it's a sane idea, but maybe give it a thought: Would it make sense to update .ts files centrally here? Is it possible at all (thinking of Chinese)?

**Comment by ann0see** [comment]
I‘d rather not do it. We can always do that in the translation cycle

**Comment by ann0see** [comment]
@gilgongo, that's another one.

**Comment by ann0see** [comment]
@gilgongo in favour of getting these PRs merged, could you please review?

**Comment by ann0see** [comment]
@henkdegroot I think this PR is an easy one to review;-)

**Review by henkdegroot — APPROVED** [review]
Changes look good to me.

**Pull request merged**
