### PR TITLE
Update Running a server webpage link in COMPILING.md file

### PR DESCRIPTION
**Pull request by jujudusud**
**Short description of changes**
Updating the following link from:
`https://jamulus.io/wiki/Running-a-Server.md#command-line-options`
to
`https://jamulus.io/wiki/Running-a-Server#command-line-options`

**Context: Fixes an issue?**
Fixes: #2418

**Does this change need documentation? What needs to be documented and how?**
No changes requiered.

**Status of this Pull Request**
Ready to be merged.

**What is missing until this pull request can be merged?**
Nothing is missing.

## Checklist
- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency)
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors.
- [x] I've filled all the content above

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
The new link works - thanks!

**Comment by jujudusud** [comment]
> The new link works - thanks!

Ready to be merged in master as soon as it has been properly reviewed.

**Comment by ann0see** [comment]
@jujudusud could you please add a CHANGELOG comment here?

**Comment by jujudusud** [comment]
Is it ok like that @ann0see?

**Comment by ann0see** [comment]
I'd add in COMPILING.md

**Pull request merged**
