### PR TITLE
Mac: Upgrade SDK and macOS version for legacy build

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Updates the SDK to an unsupported higher version for the legacy build. I think, if it builds, it builds and could maybe work. Still, we should slowly deprecate the legacy build (but not suddenly)
I've successfully built it on my repo: https://github.com/ann0see/jamulus/actions/runs/4952341059

Upgrades the legacy build to use the last supported SDK.
CHANGELOG: Mac: Upgrade legacy build to a new but unsupported SDK. This hopefully still allows the legacy build to exist, but no guarantees are given. You are advised to upgrade your OS.

**Context: Fixes an issue?**
Fixes: https://github.com/jamulussoftware/jamulus/issues/2773

**Does this change need documentation? What needs to be documented and how?**

**Status of this Pull Request**
Needs testing by someone with access to an old OS. Or at least someone with macOS. @gilgongo ?

**What is missing until this pull request can be merged?**

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [ ] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [ ] I've filled all the content above

### CODE REVIEW

**Comment by gilgongo** [comment]
I'm seeing the active tab being blank here:

image

**Comment by ann0see** [comment]
I think it's been like that for a while on modern OS.

**Comment by ann0see** [comment]
I think it's ok to get in then. (Legacy should slowly get deprecated)

**Review by gilgongo — APPROVED** [review]
Can't see anything else that might be a problem.

**Comment by ann0see** [comment]
@pljones please merge if you're ok with that. I believe that it's ok - but I can't really test it.

**Review by pljones — APPROVED** [review]
I know nothing at all about macOS.

**Pull request merged**
