### PR TITLE
update translate fr for 3.8.0

### PR DESCRIPTION
**Pull request by jujudusud**
To be merged for 3.8.0 release.

### CODE REVIEW

**Review by softins — APPROVED** [review]
Thanks!

**Review by hoffie — APPROVED** [review]
The PR looks good, thanks.

@softins @pljones I'm unsure how to go forward with this though.
- We could do an rc2 quickly. Not sure if it's worth the overhead.
- We could merge and go on without another rc (and have some low risk of breakage -- might be mitigated if this PR's artifacts are tested properly). If we go with that route, should we ping other translators on Discord quickly?

Therefore, I'm not merging yet.

**Comment by softins** [comment]
I don't think it needs another rc. I think the risk of merging this before the final release is very Low, and it's just adding translations for the few strings we were happy to leave untranslated.

But I don't think it's worth explicitly asking the other translators.

**Comment by hoffie** [comment]
> I don't think it needs another rc. I think the risk of merging this before the final release is very low, so I would include it. It's just adding translations for the few strings we were happy to leave untranslated.

Ok. Will add that to the release checklist to clarify what kind of changes are still ok in rc phase.

> But I don't think it's worth explicitly asking the other translators. Maybe just give them the opportunity if they want to.

I agree. I have added a note (without explicit pinging) in https://github.com/jamulussoftware/jamulus/issues/1595#issuecomment-843645315.

**Comment by jujudusud** [comment]
Thanks.

**Pull request merged**
