### PR TITLE
Refactoring: move src/res/translation to src/translation

### PR DESCRIPTION
**Pull request by ann0see**
This is done to find translation files quicker

**Short description of changes**

CHANGELOG: Refactoring: Move translation files one level up to make finding them easier for translators.

**Context: Fixes an issue?**

Mentioned by me in chat. The deeply nested files have annoyed me for quite some time. 

**Does this change need documentation? What needs to be documented and how?**

Yes. Contributors/especially Translators should be notified.

**Status of this Pull Request**

Discussion ready. Maybe another level/folder would be better?

**What is missing until this pull request can be merged?**

Review

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want (compiles on Linux)
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ignotus666** [comment]
Sounds good to me. I agree that a folder called 'res' three levels deep wasn't a very intuitive place to find them in ;)

**Review by ignotus666 — APPROVED** [review]

**Review by hoffie — APPROVED** [review]
I think this is an improvement. The implementation looks clean (`grep` doesn't show any matches for the old path).

**Review by softins — APPROVED** [review]
The changes look sensible, and CI is ok, so happy to approve.

I haven't done any tests myself, nor tried any of the built assets, due to lack of time.

**Comment by ann0see** [comment]
I considered this save to merge – for me nothing broke.

**Pull request merged**
