### PR TITLE
Remove Ubuntu from artifact name

### PR DESCRIPTION
**Pull request by ann0see**
Fixes: https://github.com/jamulussoftware/jamulus/issues/2429

**Short description of changes**
Removes "ubuntu" from the artifact name.

CHANGELOG: Remove confusing _ubuntu suffix from .deb files to avoid users thinking that the artifacts are only compatible with Ubuntu linux.

**Context: Fixes an issue?**
Partly fixes: #2429 

**Does this change need documentation? What needs to be documented and how?**
Yes. We need to update the installation links on the website.

**Status of this Pull Request**
Draft. 

**What is missing until this pull request can be merged?**
Needs resolving of #2429 first.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Review by pljones — APPROVED** [review]

**Review by softins — CHANGES_REQUESTED** [review]
Looking at the list of artifacts built, I don't think just removing `ubuntu` is right. All the other platforms have "win", "mac", "android", etc., in their names. Without the "ubuntu", it is not clear that these artifacts are even for Linux. But the problem is, if we replace "ubuntu" with just "linux", it implies that the packages are generically for any Linux, rather than just for Ubuntu or Debian. So I'm not sure what the best solution is.

**Comment by softins** [comment]
Since the packages are built on Ubuntu, we're only really guaranteeing that platform is compatible. We could say "ubuntu_debian", but then we would need to verify that the packages actually install and work properly on Debian 10 and 11. I'm actually leaning towards preserving the status quo.

**Comment by ann0see** [comment]
@hoffie should decide if this should be changed or not.

**Comment by hoffie** [comment]
The reason why I suggested to do this was [Debian naming suggestions](http://manpages.ubuntu.com/manpages/bionic/man1/dpkg-name.1.html):

```
root@e522311634d9:/# dpkg-name jamulus_3.8.2-1_ubuntu_amd64.deb 
dpkg-name: info: moved 'jamulus_3.8.2-1_ubuntu_amd64.deb' to './jamulus_3.8.2-1_amd64.deb'
```

However, those are only suggestions, so I don't expect this to be technically relevant.

I agree that this is just one perspective on the naming. The distinction of the different platforms in the Artifact list is very relevant as well, maybe even more relevant.

One would to satisfy both needs

**Comment by ann0see** [comment]
> Ubuntu/jamulus_3.8.2-1_amd64.deb

I doubt GitHub releases supports this. Moreover, I'm not sure if we need to stick that closely to the names? If we put it on a repo, maybe. But the file name could also be renamed there.

**Comment by hoffie** [comment]
> > Ubuntu/jamulus_3.8.2-1_amd64.deb
> 
> I doubt GitHub releases supports this.

Just tried it, looks like you're right. `/ ` is converted to a dot (`.`). So it won't work like that.

> Moreover, I'm not sure if we need to stick that closely to the names?

No, it's a suggestion/convention.

**Comment by pljones** [comment]
My main objection to using `_ubuntu` in the place it was in the name is that it can imply that the `.deb` is an _official_ Ubuntu artifact.

`Splashtop_Streamer_Ubuntu_14.04_v2.2.5.1-4_amd64.deb`

Putting it in a different place would be better -- here the "Ubuntu" isn't part of the build designator but part of the software package name.  So "Jamulus for Debian" would be "jamulus_debian_3.9.0-1_amd64.deb" (or whatever CPU).

**Comment by softins** [comment]
> My main objection to using `_ubuntu` in the place it was in the name is that it can imply that the `.deb` is an _official_ Ubuntu artifact.

I wouldn't infer that, any more than the Mac and Windows version are official from Apple or Microsoft. Just a designation of the intended target.

I would prefer to put this PR on hold for now until we've been able to think/talk a bit more about it.

**Comment by pljones** [comment]
The official debian release is named `jamulus_3.8.2+dfsg-1_amd64.deb`; any release as part of Ubuntu (rather than a ppa) that repackaged that would have "ubuntu" in the package name (as well as the Ubuntu release identifier) to indicate it was an official Ubuntu release.  ppa releases don't have "ubuntu", to show they're not official.

Windows, MacOS, etc don't use `.deb` files, so arguing their common naming conventions are different isn't really relevant.

**Comment by ann0see** [comment]
I'd be ok with merging or closing this PR (not feeling a strong need of changing it).

**Comment by ann0see** [comment]
Closing as discussion should continue in the respective issue

**Pull request closed without merging**
