### PR TITLE
Update iOS build runner from macos-11 to macos-12 in workflow

### LINKED ISSUE #3304: Github are removing macos-11 as a runner - affects iOS build
Github have deprecated macos-11 as a runner, and have said they will remove it on 28 Jun 2024.

See [this Github blog post](https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/) for the announcement.

Currently, the autobuild workflow for iOS uses the macos-11 runner, so it needs to be updated to use a later macos as the runner instead.

### PR DESCRIPTION
**Pull request by softins**
**Short description of changes**

Update the build runner for iOS from macos-11 to macos-12 in the Auto-Build workflow

CHANGELOG: Build: Updated the build runner for iOS in Github from macos-11 to macos-12

**Context: Fixes an issue?**

Fixes #3304

**Does this change need documentation? What needs to be documented and how?**
Probably not.

**Status of this Pull Request**

Ready for review. Build succeeds.

**What is missing until this pull request can be merged?**

~Maybe testing of the iOS build. Not sure how to do that.~ @ann0see has [tested the build](https://github.com/jamulussoftware/jamulus/pull/3292#issuecomment-2181351705) and reports it runs ok.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by softins** [comment]
Hmm, it looks like there is more to do to make this work. Having updated the xcode version, the build still does not succeed, with log messages that I don't understand:

```
Run QT_VERSION=5.15.2 ./.github/autobuild/ios.sh build
  QT_VERSION=5.15.2 ./.github/autobuild/ios.sh build
  shell: /bin/bash -e {0}
  env:
    MD_APPLE_SDK_ROOT: /Applications/Xcode_13.4.1.app
    JAMULUS_BUILD_VERSION: 3.10.0dev-ff6b17e
    MACOS_CERTIFICATE:
    MACOS_CERTIFICATE_PWD:
    MACOS_CERTIFICATE_ID:
    NOTARIZATION_PASSWORD:
    KEYCHAIN_PASSWORD:
    MACOS_CA_PUBLICKEY:
Info: creating stash file /Users/runner/work/jamulus/jamulus/.qmake.stash
Project MESSAGE: building version "3.10.0dev-ff6b17e" (intermediate in git repository)
2024-06-19 17:46:51.555 xcodebuild[6052:24427] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2024-06-19 17:46:51.555 xcodebuild[6052:24427] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
Command line invocation:
    /Applications/Xcode_13.4.1.app/Contents/Developer/usr/bin/xcodebuild -project Jamulus.xcodeproj -scheme Jamulus -configuration Release clean archive -archivePath build/Jamulus.xcarchive CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CODE_SIGN_ENTITLEMENTS=

User defaults from command line:
    IDEArchivePathOverride = /Users/runner/work/jamulus/jamulus/build/Jamulus.xcarchive
    IDEPackageSupportUseBuiltinSCM = YES

Build settings from command line:
    CODE_SIGN_ENTITLEMENTS =
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_ALLOWED = NO
    CODE_SIGNING_REQUIRED = NO

--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
{ platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
Prepare build
** CLEAN FAILED **
error: The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.

Build Preparation

The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.
The following build commands failed:

        Prepare build
Prepare build
(1 failure)
error: The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.
** ARCHIVE FAILED **
Build Preparation

The Legacy Build System will be removed in a future release. You can configure the selected build system and this deprecation message in File > Project Settings.


The following build commands failed:
        Prepare build
(1 failure)
Error: Process completed with exit code 65.
```

Anyone have any ideas?

If we can't make this work by 28 June, we will need to temporarily disable the iOS auto-build.

**Comment by softins** [comment]
Nope. Tried using the earliest version of xcode (13.1.0) supported under macos-12, but the build still fails with the same errors as above. I've temporarily modified the workflow to run just the iOS build while testing (1002832).

**Comment by softins** [comment]
Found there is a way to disable the legacy build system deprecation diagnostic as found in [this StackOverflow answer](https://stackoverflow.com/a/70020170), and have added that to `.github/autobuild/ios.sh` (ccc1851)

It now successfully builds on both xcode 13.1.0 and 13.4.1, so I've set it to use 13.4.1 again.

We will need to raise an issue for the need to move to the xcode "modern build system".

**Comment by ann0see** [comment]
Ok. Runs on iOS 17

**Comment by ann0see** [comment]
What would happen if you move the macOS and Xcode version even further to the latest version?

**Comment by softins** [comment]
> What would happen if you move the macOS and Xcode version even further to the latest version?

Well xcode 14 does not support the legacy build system, so builds would fail until we used a Qt version that uses the modern build system instead. I haven't investigated which versions do so.

I'm on holiday till 6 July, so have limited time, and no environment to test anything locally.

**Comment by softins** [comment]
We can't move from macos-12 to macos-13 until we support the modern build system, as macos-13 runners only offer xcode 14+

**Comment by softins** [comment]
This PR needs to be approved and merged as-is before 28 June for iOS builds to work after that date. There are two or three brownout periods before that time where they will fail too.

We can then explore later versions without the deadline.

**Comment by pljones** [comment]
Is there a related issue for this PR?  There seem to be several MacOS tooling changes and I can't tell them apart.

**Comment by ann0see** [comment]
I don't think so. This is iOS related.

**Review by ann0see — APPROVED** [review]
Tested a while ago.

**Comment by softins** [comment]
> Is there a related issue for this PR? There seem to be several MacOS tooling changes and I can't tell them apart.

There isn't at the moment. I raised the PR without creating an issue. I can do so if it provides better traceability.

#3293 is a consequence of this change, rather than an issue fixed by it.

**Comment by softins** [comment]
OK, I raised #3304 and moved the reason this PR is needed into the issue description.

**Comment by pljones** [comment]
So "iOS build runner from macos-11 to macos-12" is referring to the OS _platform_ on which the iOS build is run?  I see...  I think :)

**Comment by pljones** [comment]
Added the issue to the project board and set to In progress.

https://github.com/jamulussoftware/jamulus/pull/3065/files .github/workflows/autobuild.yml appears to have the same change as in this PR?

**Comment by softins** [comment]
> So "iOS build runner from macos-11 to macos-12" is referring to the OS _platform_ on which the iOS build is run? I see... I think :)

Yes, specifically in the Github CI.

**Comment by softins** [comment]
> https://github.com/jamulussoftware/jamulus/pull/3065/files .github/workflows/autobuild.yml appears to have the same change as in this PR?

No, that PR changes the build runner to macos-13, and the xcode to 14.2.0. Neither of those is compatible with the legacy build system needed by the build with Qt 5.

This PR is using macos-12 and xcode 13.4.1, which are the latest versions compatible with the legacy build system use by Qt 5.15.2. So this PR should be merged as an interim solution, until iOS with Qt 6 is working properly (which may well take some time).

**Review by pljones — APPROVED** [review]

**Pull request merged**
