### PR TITLE
Add missing recent contributors

### PR DESCRIPTION
**Pull request by softins**

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
Looks good to me. Maybe we should leave this open for some days to wait for input:

@drummer1154 @helgeerbe @hk1020 @reinhardwh Please comment if you want to be listed by full name instead. Just using the Github handle like it is now is fully ok as well, of course!

**Comment by reinhardwh** [comment]
Hello hoffie,
not aware of the "format" which is used. reinhardwh is ok for me.

**Comment by helgeerbe** [comment]
helgeerbe is fine for me as well.

**Comment by hoffie** [comment]
Thanks for the feedback.
This is what's currently proposed regarding the format:
https://github.com/jamulussoftware/jamulus/pull/1601/files

This list is displayed in the Jamulus UI.

**Review by pljones — APPROVED** [review]

**Pull request merged**
