### PR TITLE
Add basic translation verification check

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Executes windows installer verification script and checkkeys.pl on push to src/res/translation

**Context: Fixes an issue?**
No. There was some discussion around that. 

**Does this change need documentation? What needs to be documented and how?**
No. 

**Status of this Pull Request**
Still being tested. Probably not much to do.

**What is missing until this pull request can be merged?**
Seems to work: https://github.com/ann0see/jamulus/actions/runs/1791182911 (Although we don't seem to check for syntax errors in the win installer test yet)

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Ok. Probably an easy and little thing. Probably ready to merge.

**Comment by ann0see** [comment]
Should be squash merged

**Comment by hoffie** [comment]
Note: This was intentionally reverted in https://github.com/jamulussoftware/jamulus/commit/3343167c53f719032071b9533e5a13b50be5cc40 as far as I see.

**Comment by ann0see** [comment]
Yes only parts of it

**Pull request merged**
