### PR TITLE
Build logic: Add Qt6 compatibility

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**

This PR makes the (auto)build handling ready for Qt6. In detail:
- Autobuild: Mac: Add >=Qt6.2 bin path support
- Build: Build nsProcess as 32-bit without Qt
- Build: Split Qt/Non-Qt build env setup on Windows
- Build: Permit different Qt versions for 32/64bit Windows
- Build: Allow different Xcode versions per target
- Build: Document dmgbuild as reason for staying on macOS 10.15

**Context: Fixes an issue?**

Qt6 support, see #2299 for details.

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Ready, I'm not planning further changes right now.

**What is missing until this pull request can be merged?**

- [ ] Reviews: I suggest reviewing by commit, not (only) by full diff. I have added explanations to most of the commits. **IMPORTANT:** Do *not* squash.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [ ] ~My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency)~ 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Review by pljones — APPROVED** [review]

**Comment by hoffie** [comment]
I initially targeted all the Qt6 stuff for 3.9.0, but looking over the diff it might be safe to merge before 3.8.2rc1? What do others think?

**Comment by pljones** [comment]
I've no particular objection - albeit we've entered the beta cycle, so it's cutting down the test period for the new style of building.

**Review by softins — APPROVED** [review]
All looks good to me. I haven't run it, but the CI looks happy.

> I initially targeted all the Qt6 stuff for 3.9.0, but looking over the diff it might be safe to merge before 3.8.2rc1? What do others think?

As this is just improving the build process, I would be happy to merge it. I wouldn't want to add the code changes before 3.8.2, but I don't think you were suggesting that.

**Comment by hoffie** [comment]
Alright. I've just added a commit to add a Changelog entry and will merge today when CI is green again.

**Pull request merged**
