### PR TITLE
Autobuild: Use aqt install-qt to fix deprecation warning

### LINKED ISSUE #2278: Build: Use `aqt install-qt` instead of deprecated `aqt install`
**Describe the bug**

`aqt install` is deprecated.
`aqt install-qt` should be used instead.

**To Reproduce**

See build logs for Windows (maybe also Mac)

**Expected behavior**

No deprecation warning.

**Screenshots**

```
aqtinstall(aqt) v2.0.5 on Python 3.7.9 [CPython MSC v.1900 64 bit (AMD64)]
Warning: The command 'install' is deprecated and marked for removal in a future version of aqt.
In the future, please use the command 'install-qt' instead.
```

**Operating system**
Windows, Mac (?)

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**

`aqt install` is deprecated.
`aqt install-qt` should be used instead.

**Context: Fixes an issue?**

Fixes #2278.

**Does this change need documentation? What needs to be documented and how?**

No. Not Changelog-worthy:
CHANGELOG: SKIP

**Status of this Pull Request**

Ready.

**What is missing until this pull request can be merged?**

- [x] CI logs should be checked

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Comment by hoffie** [comment]
Checked the CI looks for Windows, Mac CodeQL und Mac. Everything looks fine, no more deprecation warnings. Ready for review.

**Review by ann0see — APPROVED** [review]
Seems ok

**Review by softins — APPROVED** [review]
Looks fine and the CI is happy, so approving.

**Comment by softins** [comment]
I see there is a conflict to resolve before merging.

**Pull request merged**
