### PR TITLE
Add debug_and_release to use separate build dirs

### LINKED ISSUE #3092: Place build generated files in separate folder
**Describe the bug**

Currently, the build generated files e.g. `.moc` are scattered in the whole root directory. This is the case especially on manual builds. 
https://github.com/jamulussoftware/jamulus/pull/2588 tried to clean them up by moving them into a separate folder however it was not successful.

This is annoying as there are a lot of files.

Please note that if the files are moved, the `.gitignore` file needs to be updated too.

**To Reproduce**

Run a build on e.g. Linux and see the files in the root.

**Expected behavior**

Have a clean root directory.

**Questions/Comments**

* Why is this a problem? I think overview is the main issue
* Cross compilation is more difficult
* Make clean removes them

### PR DESCRIPTION
**Pull request by softins**
**Short description of changes**
Adds the `debug_and_release` option to the `CONFIG` in `Jamulus.pro`. This tells `qmake` to generate separate Makefiles for Debug and Release, each using a separate sub-directory (`debug/` and `release/` respectively) for build-generated files such as `*.o` and others, instead of building them in the project root.

The user can then invoke `make` or `make release` (the default) to build a release version, or `make debug` (explicitly) to build a debug version.

This `debug_and_release` option was already the default for Windows builds, but not for other architectures.

It was necessary also to change `mac/deploy_mac.sh` to search in `Makefile.Release` instead of `Makefile` when looking for the value of `QMAKE_TARGET`.

CHANGELOG: Build: Place build files in separate directories instead of project root.

**Context: Fixes an issue?**
Fixes #3092

**Does this change need documentation? What needs to be documented and how?**
Maybe in compilation instructions, if there are any parts that would need to change as a result. Maybe not.

**Status of this Pull Request**
Ready to test

**What is missing until this pull request can be merged?**
Review and test

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Thanks. This is very nice. Builds on Debian. The old files in the root of a build don't get removed with a make clean, but that's not too bad. 
Yes, the COMPILING.md may need a small hint how to build debug.

**Comment by softins** [comment]
> The old files in the root of a build don't get removed with a make clean, but that's not too bad.

Can always switch back to `main`, then do a `make distclean`, and then switch back to this branch.

**Review by ann0see — APPROVED** [review]

**Comment by ann0see** [comment]
Approving and tagging needs documentation

**Comment by pljones** [comment]
What about `.gitignore` - does that need updating to ignore the subdirs?

What about `make distclean` - does that remove both directories?

**Comment by pljones** [comment]
Also, as `COMPILING.md` is in jamulussoftware/jamulus, updating it should be part of this change.

**Comment by softins** [comment]
> What about `.gitignore` - does that need updating to ignore the subdirs?

Good catch. I've checked the build trees I saved from the CI (see my commit b047958d7cc440db7487e1331c441146b0da9084 to see how I did so in my branch [debug-and-release-test](https://github.com/softins/jamulus/tree/debug-and-release-test)), and added a few build directories to `.gitignore` that were not there before.

> What about `make distclean` - does that remove both directories?

I can't test that, but we don't generate the actions for `make distclean`; `qmake` does that itself, so I hope it gets it right!

**Comment by softins** [comment]
> Also, as `COMPILING.md` is in jamulussoftware/jamulus, updating it should be part of this change.

Just read through it, and can't see anything that needs to change as a result of this PR. Could possibly add a brief note about `make release` vs `make debug`, but `make` already defaults to `make release`, so the compilation instructions should still be valid anyway.

**Review by pljones — APPROVED** [review]
The MacOS changes make me wonder why we do what's done but if it's needed and works, I suppose it's okay.

**Comment by pljones** [comment]
https://github.com/jamulussoftware/jamulus/issues/3322 raised for documentation.

**Pull request merged**
