### PR TITLE
Autobuild: Run CodeQL on iOS builds as well

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**

CHANGELOG: Autobuild: Enabled CodeQL for iOS builds.
(Another one to condense...)

All other platforms which have their own code paths (e.g. Android) enable it, too.

**Context: Fixes an issue?**

No.

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Ready when CI is green and CodeQL ran.

**What is missing until this pull request can be merged?**

Ready when CI is green and CodeQL ran.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Review by ann0see — APPROVED** [review]
I skipped it due to performance reasons, but if you think it should be added, we can. 

Also The build failed…

**Review by pljones — APPROVED** [review]

**Review by ann0see — CHANGES_REQUESTED** [review]
Hmm CI still failed. Probably something is wrong with CodeQl

**Comment by pljones** [comment]
I see two "errors":
```
CompileStoryboard Jamulus.xcodeproj/LaunchScreen.storyboard
    cd /Users/runner/work/jamulus/jamulus
...
    export XCODE_DEVELOPER_USR_PATH=/Applications/Xcode_12.1.1.app/Contents/Developer/usr/bin/..
    /Applications/Xcode_12.1.1.app/Contents/Developer/usr/bin/ibtool --errors --warnings --notices --module Jamulus --output-partial-info-plist /Users/runner/Library/Developer/Xcode/DerivedData/Jamulus-bdtpfrmonafyhfejbibnxopfprmh/ArchiveIntermediates/Jamulus/IntermediateBuildFilesPath/Jamulus.build/Release-iphoneos/Jamulus.build/LaunchScreen-SBPartialInfo.plist --auto-activate-custom-fonts --target-device iphone --target-device ipad --minimum-deployment-target 12.0 --output-format human-readable-text --compilation-directory /Users/runner/Library/Developer/Xcode/DerivedData/Jamulus-bdtpfrmonafyhfejbibnxopfprmh/ArchiveIntermediates/Jamulus/IntermediateBuildFilesPath/Jamulus.build/Release-iphoneos/Jamulus.build /Users/runner/work/jamulus/jamulus/Jamulus.xcodeproj/LaunchScreen.storyboard
dyld: could not load inserted library '/Users/runner/hostedtoolcache/CodeQL/0.0.0-20220224/x64/codeql/tools/osx64/libtrace.dylib' because no suitable image found.  Did find:
	/Users/runner/hostedtoolcache/CodeQL/0.0.0-20220224/x64/codeql/tools/osx64/libtrace.dylib: mach-o, but not built for platform iOS-sim
```
```
2022-03-12 08:52:23.367 ibtoold[5647:44004] [MT] DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/IDEInterfaceBuilder/IDEInterfaceBuilder-17156/InterfaceBuilderKit/Utilities/IBAbstractInterfaceBuilderPlatformToolManager.m:481
Details:  Failed to attach to IBAgent-iOS with error: Error Domain=com.apple.InterfaceBuilder Code=-1 "Encountered an error communicating with IBAgent-iOS." UserInfo={NSLocalizedFailureReason=IBAgent-iOS (5700) failed to launch and exited with status 6, NSUnderlyingError=0x7fa3b51ce320 {Error Domain=com.apple.InterfaceBuilder Code=-1 "Failed to launch IBAgent-iOS via CoreSimulator spawn" UserInfo={NSLocalizedDescription=Failed to launch IBAgent-iOS via CoreSimulator spawn, NSUnderlyingError=0x7fa3b51cdd90 {Error Domain=com.apple.InterfaceBuilder Code=-1 "Failed to handshake with platform tool" UserInfo={NSLocalizedFailureReason=Failed to open connection over FIFOs with platform tool, NSLocalizedDescription=Failed to handshake with platform tool, NSUnderlyingError=0x7fa3b51ca420 {Error Domain=com.apple.InterfaceBuilder Code=-1 "" UserInfo=0x7fa3b444de80 (not displayed)}}}}}, NSLocalizedRecoverySuggestion=Please check Console.app for crash reports for "IBAgent-iOS" for further information., NSLocalizedDescription=Encountered an error communicating with IBAgent-iOS.}
Object:   <IBCocoaTouchToolManager>
Method:   +_THREADSAFE_launchNewToolWithLaunchContext:executionContext:toolProxyClass:proxyDelegate:failureContext:requestingMethod:error:forReason:
Thread:   <NSThread: 0x7fa3b2c0bd00>{number = 1, name = main}
Please file a bug at https://feedbackassistant.apple.com/ with this warning message and any useful information you can provide.
2022-03-12 08:52:23.369 ibtoold[5647:44004] [MT] IBPlatformTool: *** Failed to launch tool with description <IBCocoaTouchPlatformToolDescription: 0x7fa3b50b1a20> System content for IBCocoaTouchFramework-ElevenAndLater <IBScaleFactorDeviceTypeDescription: 0x7fa3b2c07d80> scaleFactor=2x, renderMode.identifier=(null): Encountered an error communicating with IBAgent-iOS. (Failure reason: IBAgent-iOS (5700) failed to launch and exited with status 6): Failed to launch IBAgent-iOS via CoreSimulator spawn: Failed to handshake with platform tool (Failure reason: Failed to open connection over FIFOs with platform tool): : Failed to open FIFOs for handshaking with platform tool (Failure reason: IBAgent-iOS exited before we could handshake)
/* com.apple.ibtool.errors */
/Users/runner/work/jamulus/jamulus/Jamulus.xcodeproj/LaunchScreen.storyboard: error: Encountered an error communicating with IBAgent-iOS.
    Failure Reason: IBAgent-iOS (5700) failed to launch and exited with status 6
    Recovery Suggestion: Please check Console.app for crash reports for "IBAgent-iOS" for further information.
    Underlying Errors:
        Description: Failed to launch IBAgent-iOS via CoreSimulator spawn
        Underlying Errors:
            Description: Failed to handshake with platform tool
            Failure Reason: Failed to open connection over FIFOs with platform tool
            Underlying Errors:
                Description:
                Recovery Suggestion: Try restarting your computer
                Underlying Errors:
                    Description: Failed to open FIFOs for handshaking with platform tool
                    Failure Reason: IBAgent-iOS exited before we could handshake

** ARCHIVE FAILED **


The following build commands failed:
	CompileStoryboard Jamulus.xcodeproj/LaunchScreen.storyboard
(1 failure)
Error: Process completed with exit code 65.
```

**Comment by hoffie** [comment]
> Yep, that looks like a CodeQL for iOS issue. So maybe it's not supported? Maybe worth checking on CodeQL project.

Certainly sounds like it. The CodeQL path is x64 and iOS obviously uses arm natively. I'm unable to find documentation if iOS is supposed or not. But I don't think it's worth investing more time into this.
I guess we can just add a comment why iOS doesn't run CodeQL at the moment.

**Comment by ann0see** [comment]
Agree. I think we should add a comment saying that we don't run CodeQl on iOS since it doesn't seem to be supported. Of course we could add building for iOS intel simulator - but I don't think that makes sense.

**Comment by hoffie** [comment]
>  I think we should add a comment saying that we don't run CodeQl on iOS since it doesn't seem to be supported. 

Done via #2493. Closing this PR therefore.

**Pull request closed without merging**
