### PR TITLE
Get Translations from weblate

### PR DESCRIPTION
**Pull request by ignotus666**
These are the updates contained in a Weblate pull request that was closed due to weblate's branch being deleted.

CHANGELOG: 

**Context: Fixes an issue?**

Replaces #2921

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Preferably merged soon as until then I can't unlock the newly-created component on Weblate (conflicts would probably arise if someone were to add translations to it while this hasn't been merged).

**What is missing until this pull request can be merged?**

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [ ] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [ ] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Ah yes, and if possible, please add the correct credits.

**Comment by ignotus666** [comment]
> Ah yes, and if possible, please add the correct credits.

How do I do that?

**Comment by hoffie** [comment]
It might also be possible to fetch the original PRs commits and use those as a base.

**Comment by ignotus666** [comment]
> It might also be possible to fetch the original PRs commits and use those as a base.

Thing is, this PR is that original one + edits from Weblate that didn't make it into it.

**Comment by ann0see** [comment]
As it IS possible to merge the other PR and I did it, closing this one. Thanks nevertheless!

Will look at weblate...

**Review by ann0see — COMMENTED** [review]
I think I got the problem. Could you please rebase this PR?

**Review by ann0see — APPROVED** [review]
Looks good in general. (seems to be only an it update). This should then be squash merged...

**Comment by ann0see** [comment]
@ignotus666 how do we proceed with this PR? Can we merge it?

**Comment by ignotus666** [comment]
I just checked and it seems the Italian app translation is at 100% on Weblate, so this PR can be closed - otherwise merging it could cause conflict chaos.

**Comment by ann0see** [comment]
Ok. @dzpex @ignotus666 I’m closing this PR the.

**Pull request closed without merging**
