### PR TITLE
Upgrade Android Build OS

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

This will upgrade the OS of the Android runner to support the latest aqt version.

CHANGELOG: Upgrade Android Runner to Ubuntu 22.04

**Context: Fixes an issue?**

Related to: #3434 

**Does this change need documentation? What needs to be documented and how?**

/

**Status of this Pull Request**

Ready for review.

**What is missing until this pull request can be merged?**

Review

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. (iOS failure is expected)
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by pljones** [comment]
What does this actually affect?  Changing the host OS on which the Android build is run _should not_ change anything -- unless it's _not just_ the host OS that's changing.  Is the Android build changing in some other way - e.g. supported Android tools, minimum versions, etc, changes in Qt support?  (Yes, it's draft -- just ideas to get into the description before it's ready.)

**Comment by ann0see** [comment]
It's for potentially fixing https://github.com/jamulussoftware/jamulus/pull/3434 not finding the latest aqt.

**Comment by ann0see** [comment]
Ok. Tested on Bliss OS. And the app opens. Can't really test more though.

**Comment by ann0see** [comment]
Ok. Seems as if the aqt update will work with the OS upgrade.

**Review by pljones — APPROVED** [review]

**Comment by pljones** [comment]
OK, might as well just get it merged, then?

**Pull request merged**
