### PR TITLE
Check regional languages

### PR DESCRIPTION
**Pull request by ignotus666**
**Short description of changes**

Add check for languages in regional variation format (xx_xx). No one seemed to step forward to address this so had a go myself.

**Context: Fixes an issue?**

Fixes: #1966 

**Does this change need documentation? What needs to be documented and how?**

Not required.

**Status of this Pull Request**
Working implementation

**What is missing until this pull request can be merged?**
Alternative regular expression?

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Review by ann0see — APPROVED** [review]
Didn’t check the script, but the code seems easy.

**Comment by ignotus666** [comment]
#BLumia:

The script that checks the .nsi files reports an error with zh_cn.nsi:

```
- Checking for LangStrings diffs... WARNING, differences found:
--- /dev/fd/63	2021-09-09 12:02:43.988161262 +0200
+++ /dev/fd/62	2021-09-09 12:02:43.989161256 +0200
```

Looking at it, it seems to have fewer LangStrings than the other languages. Not sure if the error is caused by that.

**Comment by BLumia** [comment]
> The script that checks the .nsi files reports an error with zh_cn.nsi:
> 
> ```
> - Checking for LangStrings diffs... WARNING, differences found:
> --- /dev/fd/63	2021-09-09 12:02:43.988161262 +0200
> +++ /dev/fd/62	2021-09-09 12:02:43.989161256 +0200
> ```
> 
> Looking at it, it seems to have fewer LangStrings than the other languages. Not sure if the error is caused by that.

Some new strings are added after my translation patch (within 15fe013e9a4e) that need to be translated. I will send a patch to translate the new strings later, but I am also not sure if the error is caused by that.

**Comment by ignotus666** [comment]
Just checked by adding dummy translations for the missing LangStrings and the error goes away.

**Comment by BLumia** [comment]
See #2008.

**Comment by gilgongo** [comment]
If this gets merged, #2008 also has to go in, otherwise the script throws an error (acc. @ignotus666)

**Pull request merged**
