### PR TITLE
Update Qt version to 5.15.2 in deploy_windows script, align with autobuild

### LINKED ISSUE #1719: Inconsistency in deploy_windows.ps1 script
**Describe the bug**
The deploy_windows.ps1 script contains the following lines:
    [string] $QtInstallPath = "C:\Qt\5.12.3",
    [string] $QtCompile32 = "msvc2019",
    [string] $QtCompile64 = "msvc2019_64",

For Qt 5.12.3, the Qt Compile folders are msvc2017 (not msvc2019).
The locations used here are the ones for Qt 5.15.2.

**Expected behavior**
QtInstallPath should be updated to 5.15.2. This will makes the scripts also equal to the autobuild.

**Operating system**
Win10

**Version of Jamulus**
v3.8.0

### PR DESCRIPTION
**Pull request by henkdegroot**
Fixes #1719

### CODE REVIEW

**Review by pljones — APPROVED** [review]

**Review by ann0see — APPROVED** [review]
Although I didn't test it, it should be ok.

**Comment by ann0see** [comment]
I think this can go into the current release? If not, please tag it correctly and merge later.

**Comment by hoffie** [comment]
> I think this can go into the current release?

I agree -- this PR should not change anything in the officially built releases, so it'd be fine, IMO. Leaving it open for others to comment. This can be merged last-minute, IMO.

**Comment by jujudusud** [comment]
@henkdegroot , To be exhaustive, we have to take a look at :

- lines 151 to 154,
- lines 187 and 188,
- lines 193 to 195.

Thanks.

**Comment by henkdegroot** [comment]
Update made to the message in the script which is thrown when the Qt Binaries are not found.
Thanks for @jujudusud  for the suggestion!

Message now shows the path being referenced and hints 2017 or above.

**Review by ann0see — APPROVED** [review]
Looks ok for me (not tested)

**Comment by ann0see** [comment]
Merging in order to get ready for the next release.

**Pull request merged**
