### PR TITLE
Update translation_zh_CN.ts

### PR DESCRIPTION
**Pull request by BLumia**
Resolve GH-2702

### CODE REVIEW

**Comment by pljones** [comment]
Thanks for this (and especially for spotting the "Now a directory server" error in the English).  Is there anyone you know who could review it here (on Github)?

**Review by ann0see — COMMENTED** [review]
It looks consistent, I doubt we have any chinese reviewer?

**Comment by ann0see** [comment]
- [x] Translator listed in the `src/util.cpp`
- [x] Punctuation and spacing consistent 
- [x] Signal words consistent ("ASIO", "Buffer") 
- [ ] No untranslated strings (`grep unfinished -5 src/translation/translation_$TRANSLTION*.ts`) (todo)
- [x] Only a single `.ts` file checked in (+ Installer translations)

**Review by pljones — APPROVED** [review]
Approved without understanding. :)

**Pull request merged**
