### PR TITLE
Refactoring: Move images to src/res (Windows and Mac)

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

Moves images from their OS folders to src/res. Note: Android and Linux will follow since they seem to be more complicated.

CHANGELOG: Refactoring: Moved around files to clean up the repository

**Context: Fixes an issue?**

Related to: https://github.com/jamulussoftware/jamulus/pull/2601

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Ready review. Unfortunately due to #1841 I can't test it locally on macOS, but I tested the CI version.

- [x] macOS: Server and Client show correct icons
- [x] Windows Installer: Installer icon shows up
- [x] Windows Installer: Installer banner and welcome page with ASIO compatible shows up on ASIO build, and Installer banner only shows up on JACK build.
- [x] Start menu installer, uninstaller, ... and task-bar all show the correct server/client icons (ASIO and JACK)

**What is missing until this pull request can be merged?**

Nothing

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [ ] I've filled all the content above

### CODE REVIEW

**Comment by pljones** [comment]
> = src/res/...

Part of me still wants to be able to glance at the resources and know what they're for (i.e. used in Jamulus on platform X, used in the installer on platform Y, etc).  So it might be good to take this opportunity to improve the naming for clarity, as well as moving them.

**Comment by ann0see** [comment]
Ok. Once this is finished, we need to re-test macOS and Windows icons.

**Review by pljones — APPROVED** [review]
Approving.  Not sure why the ARMHF build wasn't happy.

**Comment by ann0see** [comment]
I've opened https://github.com/jamulussoftware/jamulus/issues/2837

**Comment by ann0see** [comment]
> Ok. Once this is finished, we need to re-test macOS and Windows icons.

Done and they still show up correctly.

**Review by hoffie — APPROVED** [review]
Looks sane, `grep` didn't find any more mentions of the old file names.

**Pull request merged**
