### PR TITLE
Upgrade NSIS to v3.08

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

Upgrade NSIS to 3.08.

**Context: Fixes an issue?**
Might fix autobuild failures. But I doubt it...

**Does this change need documentation? What needs to be documented and how?**

No

**Status of this Pull Request**
Not yet fully tested.

**What is missing until this pull request can be merged?**
Installation on Windows 

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Comment by henkdegroot** [comment]
@ann0see, I noticed the comment in the deploy_windows.ps1 script related to the redirect URL for sourceforge downloads.
The link in the powershell takes me to an article at powershellmagazine. Here there is also a comment placed with a reference to a fix. I.e. that you need to include a "close" to prevent time-out to occur. Perhaps this is what is missing in our script?
When I tried the current function in our script a few times, I indeed get to a point that I don't get the redirected URL.
When I use the function as provided in the comment, I can call as many times as I want and always get the redirected URL.

It may have been luck this time...but sounds like that could be an improvement to test?
Another thing which probably can be build in the script is a check to see if there was actually something downloaded or not and then perform a retry if not?

**Comment by ann0see** [comment]
If this modification solves the issue it would be good to implement that. However we might also host the NSIS file in jamulussoftware/assets

**Review by softins — APPROVED** [review]
Looks fine to me, and I've done a test download from the URL. Plus the CI is happy.

**Comment by softins** [comment]
I have also just downloaded the Windows installer produced by the CI, and it installs without issues. This can probably be marked as **Ready for review**.

**Review by pljones — APPROVED** [review]

**Pull request merged**
