### PR TITLE
Autobuild: Fix broken .deb dependencies / Fix uninstallable 3.8.2 on Ubuntu 18.04

### LINKED ISSUE #2422: Ubuntu 18.04: Version 3.8.2 fails to install due to bad dep libgcc-s1 (>= 3.0)
### Discussed in https://github.com/jamulussoftware/jamulus/discussions/2416

Tried to update server to 3.8.2

Error returned:

root@rv2575:~# sudo apt install ./jamulus_headless_**3.8.2**_ubuntu_amd64.deb
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Hinweis: »jamulus-headless« wird an Stelle von »./jamulus_headless_3.8.2_ubuntu_amd64.deb« gewählt.
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 jamulus-headless : Hängt ab von: **libgcc-s1 (>= 3.0) ist aber nicht installierbar**
E: Probleme können nicht korrigiert werden, Sie haben zurückgehaltene defekte Pakete.

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**

The autobuild-produced Debian/Ubuntu packages use another `debian/control` file than manual builds. This is done by copying a special copy of the `control` file to the right place.

86807c1ab88ee10ab453371b45d3a4e8a45fd606 (squash of 3dadf23968ec58b22d1ff7b632f23732409bdfa7 and others) from #2138 mistakenly (I think?) removed this logic.

This results in broken dependencies (especially visible on Ubuntu 18.04) and wrong maintainer information:
```
root@71dafa5ca28f:/downloads# dpkg-deb --info jamulus_headless_3.8.1_ubuntu_amd64.deb | grep -P 'Depends|Maintainer'
 Maintainer: "corrados" <nomail@example.com>
 Depends: libqt5core5a (>= 5.5.0), libqt5network5 (>= 5.0.2), libqt5xml5 (>= 5.0.2)

root@71dafa5ca28f:/downloads# dpkg-deb --info jamulus_headless_3.8.2_ubuntu_amd64.deb | grep -P 'Depends|Maintainer'            
 Maintainer: "Marc Landolt jr" <debian@marclandolt.ch>
 Depends: libc6 (>= 2.27), libgcc-s1 (>= 3.0), libqt5core5a (>= 5.9.0~beta), libqt5network5 (>= 5.8.0), libqt5xml5 (>= 5.0.2), libstdc++6 (>= 7), adduser
```

We should also **decide what to do regarding 3.8.2**:
1. Take the new 3.8.2 .deb (app version remaining at 3.8.2) from this PR, remove the existing .deb from the release and upload the new one (maybe with a -1 suffix to make clear that the file has been updated)
1. Release 3.8.3 as a bug fix release. Downside: Will trigger irrelevant update notifications and confusion for non Ubuntu-18.04 users
1. Release 3.8.2.1. Downside: We've never tested this versioning scheme. I wouldn't do that.
1. Release 3.9.0nightly and point Ubuntu 18.04 users to this version (maybe add hint to the announcement)
1. Do nothing and state "3.8.2 is broken on Ubuntu 18.04; please use 3.8.1 and wait for the next release". Ubuntu 18.04 is really old, but still supported until 2023. People do use it as #2422 shows.

I'd tend towards option 1.

**Context: Fixes an issue?**

Fixes #2422

**Does this change need documentation? What needs to be documented and how?**

Yes:
- [ ] Release body
- [ ] Github Announcement
- [ ] Facebook announcement

**Status of this Pull Request**

Needs verification/testing.

**What is missing until this pull request can be merged?**

Needs verification/testing.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [ ] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Comment by hoffie** [comment]
The [deb](https://github.com/hoffie/jamulus/suites/5409403458/artifacts/170815896) from https://github.com/hoffie/jamulus/actions/runs/1884500159 (0f9e948) installs for me on Ubuntu 18.04 (should be identical to this PR's artifact). So this PR fixes #2422.
As my PR is based on r3_8_2, this PR's checks will already generate a file which we could use for option (1) mentioned above.

**Comment by hoffie** [comment]
@npostavs If you could have a look here to confirm that the `debian/control` modification was really an unintended change, this would be highly appreciated. If it was intended we will likely have to find another fix.

**Comment by hoffie** [comment]
>  As my PR is based on r3_8_2, this PR's checks will already generate a file which we could use for option (1) mentioned above.

Hmm, for some reason¹ the checks in this PR list a totally different commit ID than my branch: https://github.com/jamulussoftware/jamulus/runs/5296375135?check_suite_focus=true

Therefore, we can't use those packages 1:1. This run on my repo/branch would work though: https://github.com/hoffie/jamulus/actions/runs/1884500159

¹ Maybe some auto-rebase by Github?

**Comment by npostavs** [comment]
> @npostavs If you could have a look here to confirm that the debian/control modification was really an unintended change, this would be highly appreciated. If it was intended we will likely have to find another fix.

Hmm, I think I copied it from @ann0see's patch in #1767; I agree it looks like a mistake.

**Review by ann0see — APPROVED** [review]
Yes. Seems like a mistake. I would replace the deb file and give a small announcement

**Comment by pljones** [comment]
Yep, I'd go with "a -1 suffix" -- assuming the default deb didn't have a suffix.  Otherwise, increment the suffix.

lwks-12.5.0-amd64.deb would go to lwks-12.5.0-1_amd64.deb for a patch release.
mysql-apt-config_0.3.2-1ubuntu14.04_all.deb would go to mysql-apt-config_0.3.2-2ubuntu14.04_all.deb for the second patch release.

**Comment by hoffie** [comment]
> Yep, I'd go with "a -1 suffix" -- assuming the default deb didn't have a suffix. Otherwise, increment the suffix.

If we wanted to do that properly (probably a good idea...), then we'll have to bump debian_revision via an additional changelog entry: https://docs.huihoo.com/debian/manuals/maint-guide/ch-update.en.html#s-newrevision

I can do that on a temporary tag or branch.

**Comment by pljones** [comment]
OK, so:
- we need the actual fix merged to master.  But that won't create a 3.8.2 release build
- we need an "actual" 3.8.2 release build with "_1" appended (in full, something like `jamulus_3.8.2_1ubuntu_amd64.deb`
- that needs building somehow

Then, once it's built, we need the existing 3.8.2 release note updated.

(Should we be using "ubuntu" in the .deb name, by the way?)

Right?

**Comment by softins** [comment]
I've also verified on a new Ubuntu18 VM that the current release debs don't install, and @hoffie's ones from https://github.com/hoffie/jamulus/actions/runs/1884500159 do install fine.

**Comment by pljones** [comment]
Ideally our CI/CD processes would catch things like this as regressions to stop them happening again.

**Comment by ann0see** [comment]
Certainly testing like that is possible. But how would we check this specifically?

**Comment by pljones** [comment]
The deploy would fail.  If it fails, it needs fixing.  It could fail for many reasons.  It could install and still not work, hence the "can a client connect" check.  We're not checking a "real" deploy - with firewalls, etc - just a sanity check.

**Comment by ann0see** [comment]
ok. So something like
1. install .deb file
2. spin up server (jamulus -n - s -T [other args to check] &)
3. connect to localhost headless (jamulus -n -c localhost -6 [...])
4. if exited with non zero exit code: fail ci else (kill after x seconds)

**Comment by pljones** [comment]
Yeah.  I don't know how headless _client_ works too well, to be honest - the "zero status code" might be tricky :).

**Comment by ann0see** [comment]
Yes. That’s why a timeout would be good. Or we could abuse json-rpc

**Comment by pljones** [comment]
> Or we could abuse json-rpc

Having that in would really help for testing.

**Comment by hoffie** [comment]
@pljones @ann0see I've opened #2428 to track the CI idea.

> (Should we be using "ubuntu" in the .deb name, by the way?)

I wondered about that as well. It think it should not. I've opened #2429 for that.

**Comment by softins** [comment]
> Certainly testing like that is possible. But how would we check this specifically?

Well this issue was the debs were uninstallable. Since we are building on a fresh ubuntu-18, it should be possible just to try `apt install` the built debs within the same container, and raise an error if they fail. That would have caught this issue without needing to try running the installed binary.

**Comment by ann0see** [comment]
CHANGELOG: BUG: Allow Jamulus being installed on Ubuntu 18.04. This dependency issue has already been fixed for the release before but is now officially part of the upstream build process.

**Comment by ann0see** [comment]
@pljones I just shortened the changelog.

**Comment by pljones** [comment]
"(ported from last release to upstream)" is wrong.  We don't have an upstream.  If someone else who packages our build changes our build, they are _downstream_ of us and we're backporting.

**Comment by ann0see** [comment]
I think the issue only appeared on this specific version. 
As far as I remember, what really happened was that the release was fixed first and then the fix was applied to master. So it's about our packaging

**Comment by ann0see** [comment]
That’s also ok.

**Pull request merged**
