### PR TITLE
Remove translation from CLI version text

### LINKED ISSUE #2319: Translation of GPL preamble in GUI and CLI
**Describe the bug**

Status quo:
- The GPL preamble in *About Jamulus* is in English (untranslated). The newly added GPL preamble in `--version` output is translated. That's inconsistent.
- The way of implementing the translation is non-optimal for translators as pointed out by @BLumia in https://github.com/jamulussoftware/jamulus/pull/2313#discussion_r794258387

**To Reproduce**

- Compare *About Jamulus* with `--version`
- or: Perform translations

**Expected behavior**

We should:
- [ ] Decide if this text should be translated at all. For context: `cat --version` translates it.
- [ ] If we do translate, the GUI version should be translated as well (it would be more natural for the command line version not to be translated as other command line outputs aren't translated either).
- [ ] If we wanted to show a translated version on CLI, we would have to load translations, which are [currently loaded for GUI runs only](https://github.com/jamulussoftware/jamulus/blob/master/src/main.cpp#L813).
- [ ] @BLumia suggested using a single `tr ( )` call with included new lines (`\n`). This sounds good to me. There's also the possibility to pass comments to translators such as *"Please align to X characters"* (the status quo value for X is rather wide...?). The way to pass such a comment to translators seems to be to use a special [`//: Comment which is transferred to .ts files by lupdate`](https://doc.qt.io/qt-5/i18n-source-translation.html#translator-comments).

**Version of Jamulus**

3.8.2_beta1

**Additional context**

I'm not keen on decoding this, I'm fine either way, but we should be consistent and make life easier for translators.

### PR DESCRIPTION
**Pull request by henkdegroot**
**Short description of changes**
Remove the translation for the CLI version text output

CHANGELOG: Client: Remove the translation for the CLI version text output

**Context: Fixes an issue?**
Fixes #2319 

**Does this change need documentation? What needs to be documented and how?**
No

**Status of this Pull Request**
Waiting on second review

**What is missing until this pull request can be merged?**
Nothing

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by henkdegroot** [comment]
Sample of the CLI version output in windows:

image

**Review by ann0see — COMMENTED** [review]
Thanks! One time we should also add the uses ASIO/copyright statement conditionally.

**Review by ann0see — APPROVED** [review]

**Comment by henkdegroot** [comment]
Asio text to be added as part of the Asio PR I will be doing for updating the installer and About dialog.

**Comment by ann0see** [comment]
@hoffie could you please review this PR?

**Review by pljones — APPROVED** [review]

**Pull request merged**
