### PR TITLE
Add connect to server help message

### PR DESCRIPTION
**Pull request by ann0see**
Might solve #847

Todo: Wording of the sentence, translation (but that's something for the next release). 

Maybe we could use: Setup your audio, connect and start jamming!

Not Connected to a server:

ConnectServer

Connected:
Connected

### CODE REVIEW

**Comment by ann0see** [comment]
@dcorson-ticino-com I think this would be a "quick" fix for your feature request. I've now also added the "gray out input levels if not connected" feature. Probably a re-arrangement of the UI would be good, but I think that's far from finished now. Also I'd personally like to have incremental changes with this and #973 being small ones.

**Comment by pljones** [comment]
"Setup" should be two words.
"Set up your audio" only happens once, so shouldn't be a "nag" like this - first time installation hand-holding only.

**Comment by ann0see** [comment]
> I'd also prefer it as replacing "Server" in the group box title, rather than as a separate label like you've shown.

The problem with this would be that it's probably a lot less visible.

**Comment by pljones** [comment]
The first time user process shouldn't be part of Jamulus at all.  It's only needed once.

**Comment by dcorson-ticino-com** [comment]
To reduce the nagging a bit I would make the message only shown at program start-up before the first connection.
I agree that the audio setup should only be at installation time.  Would a bool in the ini file be an adequate way of seeing this?
D

**Comment by gene96817** [comment]
Sometimes another application might make changes to the underlying system that affects Jamulus. Will there be an easy way to repeat the first time set up? This is also useful for a new user that didn't get the right results in their first connection. Then we/I need to handhold them through the first time set up (again) to get the process right.

**Comment by ann0see** [comment]
@gene96817 unfortunately the first time setup doesn't exist yet. Can you open an issue and describe what you'd like? We can then discuss everything there.

**Comment by ann0see** [comment]
Just changed Setup to Set up. Any chance this will be part of the next release?

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
@pljones I hope you know that this will also gray out the level meter if you're not connected.

**Comment by pljones** [comment]
Yes, I saw that.  I think it makes sense.  When Jamulus isn't connect to a server, it _should_ have the sound card closed.  (On Windows, it doesn't have the ASIO driver open when it's not connected to the server.  It should _not_ connect to JACK except when connected to a server, either, to avoid putting load on the system unnecessarily.  No idea on MacOS.)

**Comment by ann0see** [comment]
> I consider current behaviour ... unhelpful

That makes two of us. Probably a larger todo for the next release. 

What I would suggest:

If ASIO/Jack/... wasn't found or doesn't work (wrong sample rate,...): open Jamulus but give a clear warning what is wrong. Add a button which opens settings,... Do you want to open a new issue on this?

**Comment by atsampson** [comment]
>  It should not connect to JACK except when connected to a server, either, to avoid putting load on the system unnecessarily

I'm not sure this is a huge worry - Jamulus doesn't do very much in its JACK callbacks when it's not connected to a server, so the additional load from this is pretty minimal. From a very rough measurement on my machine, jackd takes 0.7% CPU when nothing's connected, and Jamulus takes 0.3% when idling. For people like me who have Jamulus connected to non-default JACK ports, you'd also need some external mechanism for remaking your connections every time you connect to a server, which would be possible but a bit more work.

**Comment by gene96817** [comment]
(I don't have a Windows machine so I can't reconfirm this behavior.)
It seems the Windows machines can only have one application access the microphone. This means it matters if Jamulus is open before Zoom or visa versa. If the closes its connection to the sound card, does this mean Jamulus might not be able to get a connection (because another application has taken control)? This is not an issue on Macs.

**Comment by ann0see** [comment]
Did you try ASIO4ALL v2.13? For me, I think it partly "fixed" this error

**Review by softins — APPROVED** [review]

**Comment by pljones** [comment]
> It seems the Windows machines can only have one application access the microphone.

This is completely dependent on the driver in use.

**Comment by gene96817** [comment]
All those "dependent on" makes it so hard to give assistance.  :(

**Pull request merged**
