### PR TITLE
Add Unicode Copyright symbol to Copyright notice

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

Changes the Copyright symbol to the unicode equivalent

Copyright screen

CHANGELOG: SKIP 

**Context: Fixes an issue?**

Fixes: #2903
**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**
Ready for review.

**What is missing until this pull request can be merged?**

Nothing.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by pljones** [comment]
This doesn't address the start up banner, then?
```
 *** Copyright (C) 2005-2023 The Jamulus Development Team
```
Also, the `©` symbol can also be expressed (in the `.ui` file) as `&copy;`, which might be easier to edit.
https://www.rapidtables.com/web/html/html-codes/html-code-copyright.html

**Comment by ann0see** [comment]
```
/usr/lib/qt5/bin/uic src/aboutdlgbase.ui -o ui_aboutdlgbase.h
uic: Error in line 72, column 34 : Entity 'copy' not declared.
File 'src/aboutdlgbase.ui' is not valid
```
I don't think so.

**Comment by ann0see** [comment]
Fixed the other situation too. I hope Windows supports unicode characters in terminal.

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
I'm going to merge this now.

**Pull request merged**
