### PR TITLE
Android: Update Oboe to v1.7.0

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

Updates Oboe to v1.7.0 (a stable build not the intermediate commit)

CHANGELOG: Android: Updated Oboe to version 1.7.0

**Context: Fixes an issue?**

/

**Does this change need documentation? What needs to be documented and how?**
Probably not.

**Status of this Pull Request**

Ready for testing (I don't have access to an android device at the moment)

**What is missing until this pull request can be merged?**

Review of changes of oboe code if needed. 

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want (Don't have access to Android at the moment. However tested by pljones)
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [ ] I've filled all the content above

AUTOBUILD: Please build all targets

### CODE REVIEW

**Comment by ann0see** [comment]
Status: Needs someone with access to Android.

**Comment by pljones** [comment]
I'll try explaining to my phone it wants to install this.

**Comment by pljones** [comment]
Can you rebase?  The builds have expired.

**Comment by pljones** [comment]
OK, the build runs (and processes audio - I get nice whistling feedback... hence muting myself in the mixer).

**Comment by ann0see** [comment]
The Drive link is restricted. 

However, from your post I think it's ok?

**Comment by pljones** [comment]
> The Drive link is restricted.

Cut'n'paste goof...

**Comment by ann0see** [comment]
If it works, please merge it.

**Pull request merged**
