### PR TITLE
Remove unneeded variable in deploy_mac.sh

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Codacy notified me that there's a unneeded variable in deploy_mac.sh. This should be removed

CHANGELOG: SKIP

I don't think this needs to be part of the change log.

**Context: Fixes an issue?**
No

**Does this change need documentation? What needs to be documented and how?**
No

**Status of this Pull Request**
Ready (waiting on CI)

**What is missing until this pull request can be merged?**
Nothing

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
Thanks!

**Comment by ann0see** [comment]
CI failed for the windows JACK build. I think we should re-run this.

**Comment by hoffie** [comment]
Hm, [failure in `choco install jack` for 32bit, but I don't see why](https://github.com/jamulussoftware/jamulus/runs/5397004089?check_suite_focus=true#step:7:65) (no download issues -- but that's usually hidden anyway).
Certainly unrelated to this PR, but still strange.
Note: actions/cache kicked in, so I'm even less sure why this happens. Let's see what the second run does.

**Comment by hoffie** [comment]
Second run worked, so unless this repeats, I'd write it off as some Github/connectivity glitch (maybe choco still tries to check some metadata remotely).

**Comment by ann0see** [comment]
@hoffie I just made a few quoting changes found by Codacy. I think they can also go in with this PR.

**Review by pljones — APPROVED** [review]

**Pull request merged**
