### PR TITLE
Settings UI changes for ASIO

### PR DESCRIPTION
**Pull request by mulyaj**
Renamed "ASIO Setup" to "ASIO Device Settings" and created a QTgroupbox for devices.

### CODE REVIEW

**Comment by ann0see** [comment]
@mulyaj I think you need to open this PR based on the MoveASIO branch not on master.

**Comment by mulyaj** [comment]
Yeah I did something wrong here... can you remove this?

**Comment by ann0see** [comment]
Wait a moment, I'll try to do a git cherry-pick here.

**Comment by mulyaj** [comment]
I'm not sure how to just get the UI and cpp changes I made to PR.

**Comment by ann0see** [comment]
This happens because these changes are based on master and the MoveASIO branch is not up to date with master. Let me check it.

**Comment by mulyaj** [comment]
Oh I see, thanks.

**Comment by ann0see** [comment]
See #1000

**Comment by mulyaj** [comment]
Cool! Appreciate it.

**Comment by ann0see** [comment]
Just merged it. I assume this is your first PR here? Thank you very much ;-)!

You should add yourself to the contributor list. I'll link to it shortly.

**Comment by ann0see** [comment]
Ok. You should add yourself to this file now: https://github.com/jamulussoftware/jamulus/blob/master/src/util.cpp

Just add the main repo via 

`git remote add upstream git@github.com:jamulussoftware/jamulus`

`git fetch upstream`
`git checkout upstream/master` (I hope this is correct)
`git checkout -b "AddContributor"`

Then do your changes, push it and open a PR here.

**Comment by mulyaj** [comment]
Ok, will do

**Pull request closed without merging**
