### PR TITLE
Build: Unify headless package name and binary

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

CHANGELOG: Renamed headless .deb file to `jamulus-headless_[version]_ubuntu_[arch].deb` for consistency with binary. This might need changes to scripts downloading this `.deb` file.

**Context: Fixes an issue?**

Fixes: https://github.com/jamulussoftware/jamulus/issues/2429

**Does this change need documentation? What needs to be documented and how?**

Yes. Will open a PR on the documentation

**Status of this Pull Request**

Ready for review

**What is missing until this pull request can be merged?**

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Review by hoffie — COMMENTED** [review]
Looks fine to me, but as it is a breaking change I'd rather postpone it to 3.10.0?

**Comment by ann0see** [comment]
We can, but it's not in any official script, I think?

**Comment by pljones** [comment]
Yeah, I'm tempted to just go with it.  If Simon's doc or some script fails, then the maintainer of the script gets to update it.  We provide our own doc -- and _*that*_ better be correct...

**Review by hoffie — APPROVED** [review]
Ok. ;)
Can someone ping those with known scripts here though?

**Comment by ann0see** [comment]
Probably @sthenos and @softins ?

**Review by pljones — APPROVED** [review]
It builds.  If it breaks third-party scripts, so be it.  Unless we actually hear from people, we go ahead.

**Pull request merged**
