### PR TITLE
Add transparency to vibraphone icon

### PR DESCRIPTION
**Pull request by softins**
**Short description of changes**

Updates the vibraphone icon (introduced in #2080) to include a transparent background.

**Context: Fixes an issue?**

With the original vibraphone icon, the channel label looks like this: 
image

With the replacement icon, it looks like this: 
image

All the other instrument icons already have a transparent background.

**Does this change need documentation? What needs to be documented and how?**

No documentation changes.

**Status of this Pull Request**

Tested and working.

**What is missing until this pull request can be merged?**

Ready to merge.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Comment by pljones** [comment]
Can you show it in Compact, too, compared with some of the other icons, preferably (e.g. guitar/vocals).

**Comment by softins** [comment]
> Can you show it in Compact, too, compared with some of the other icons, preferably (e.g. guitar/vocals).

Sure, I haven't changed the icon size (except reduced the height from 28px to 27px to match all the others), just its transparency.

Here is the old icon in Fancy mode: 
image
And Normal mode:
image
And Compact mode:
image

Now the new icon in Fancy mode:
image
And Normal mode:
image
And Compact mode:
image

**Review by pljones — APPROVED** [review]
Yup, looks better.  So now icon reviews need:
- ideally all platforms
- all fader sizes
- all background shades (to avoid things like a pale green icon "vanishing"...)

**Comment by softins** [comment]
I don't think there's anything contentious here, so I'll just merge as admin with one approval.

**Pull request merged**
