### PR TITLE
Clean up DISTFILES

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

Removes and adds references to removed/moved files in Jamulus.pro
CHANGELOG: SKIP

**Context: Fixes an issue?**

Fixes: #3345 

**Does this change need documentation? What needs to be documented and how?**

No
**Status of this Pull Request**

`make dist` was tested by @softins 
**What is missing until this pull request can be merged?**

Review
## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Review by softins — APPROVED** [review]
Ah yes, I forgot about that reference. Good catch.

**Review by softins — CHANGES_REQUESTED** [review]
Actually, `make dist` throws up some other errors too, which are probably additional obsolete filenames:
```
cp: cannot stat 'src/res/CLEDBlack.png': No such file or directory
cp: cannot stat 'src/res/CLEDDisabledSmall.png': No such file or directory
cp: cannot stat 'src/res/CLEDGreen.png': No such file or directory
cp: cannot stat 'src/res/CLEDGreySmall.png': No such file or directory
cp: cannot stat 'src/res/CLEDRed.png': No such file or directory
cp: cannot stat 'src/res/CLEDYellow.png': No such file or directory
cp: cannot stat 'src/res/LEDBlackSmall.png': No such file or directory
cp: cannot stat 'src/res/LEDGreenSmall.png': No such file or directory
cp: cannot stat 'src/res/LEDRedSmall.png': No such file or directory
cp: cannot stat 'src/res/LEDYellowSmall.png': No such file or directory
cp: cannot stat 'src/res/HLEDGreenSmall.png': No such file or directory
cp: cannot stat 'src/res/HLEDBlackSmall.png': No such file or directory
cp: cannot stat 'src/res/HLEDRedSmall.png': No such file or directory
cp: cannot stat 'src/res/HLEDYellowSmall.png': No such file or directory
cp: cannot stat 'libs/opus/INSTALL': No such file or directory
make[1]: *** [Makefile.Release:1163: distdir] Error 1
make[1]: Leaving directory '/home/tony/jamulus'
make: *** [Makefile:299: release-distdir] Error 2
```

**Comment by softins** [comment]
> Actually, `make dist` throws up some other errors too, which are probably additional obsolete filenames:

Looks like at least some of them date from 7e758423f8189769448509c51add7f73118a4158. I'll check the list from scratch.

**Comment by softins** [comment]
I've pushed an update that removes obsolete filename from the list and adds some that were missing. `make dist` now works, although I'm not sure how useful the produced tarball is nowadays.

We should update the PR title/description to reflect the wider scope of the changes.

**Review by softins — APPROVED** [review]

**Comment by ann0see** [comment]
Thanks.

**Comment by softins** [comment]
Why is this 3.12.0 and not 3.11.0? Given that it's fixing something that's incorrect, and doesn't affect the application code or translations.

**Comment by ann0see** [comment]
We're just conservative on tagging things after freeze.

**Comment by ann0see** [comment]
Anyway, retagged

**Review by pljones — APPROVED** [review]

**Pull request merged**
