### PR TITLE
Build: Windows: Fix Github JACK build failures & improve build speed

### LINKED ISSUE #3035: New JACK autobuild fails on GitHub Actions Pull Requests
**Describe the bug**

The JACK build fails on GitHub Actions PRs if Workflow Permissions are set to "Read repository contents and packages permissions". No fail can be seen on PRs by me/if "Read and write permissions" are set.
**To Reproduce**
https://github.com/jamulussoftware/jamulus/pull/3031 with "Read repository contents and packages permission" set doesn't fail but https://github.com/jamulussoftware/jamulus/pull/3011 does. 
This is a successful run while write permissions were enabled: https://github.com/jamulussoftware/jamulus/actions/runs/4515448402/jobs/7952904802

**Expected behavior**

No matter what permissions are set the JACK build succeeds for GitHub actions and other contributors. 

**Screenshots**

/
**Operating system**

Windows on GH
**Version of Jamulus**

/
**Additional context**

I strongly believe this is a permission error we miss a setting or Autobuild permission somewhere. Something related to GH_TOKEN maybe?

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**
- **Autobuild: Ensure JACK install completion**
  Previously, the JACK installers were started as ordinary programs. As they are GUI applications, they detach from the console and the powershell build script (and Github Actions) continues. Therefore, once the actual build starts, the JACK installation may not have finished at all. This commit uses Powershell's Start-Process -Wait feature to wait for completion before continuing.

- **Build: Windows: Improve dependency download speed**
  Invoke-WebRequest enables a progress bar by default which slows down the requests a lot. Disabling these makes the build run much faster.
  Source:
  - https://stackoverflow.com/a/43477248
  - Interactive testing

CHANGELOG: SKIP

**Context: Fixes an issue?**
Fixes  #3035.

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Ready on CI green.

**What is missing until this pull request can be merged?**
CI.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. (Except for MacOS Legacy which seems to be broken anyway)
-  [x] I've filled all the content above

AUTOBUILD: Please build all targets

### CODE REVIEW

**Review by ann0see — COMMENTED** [review]
Thanks for this! Strange that the progress bar introduces delay. 
Will check this PR on my repo.

**Comment by hoffie** [comment]
> Thanks for this! Strange that the progress bar introduces delay. Will check this PR on my repo.

Just to be clear: the progress bar is only an improvement, the actual fix is the `-Wait`.

**Comment by ann0see** [comment]
Yes. I've read the stackoverflow link now. 

--
For the bug:
Set the permissions to more restrictive on this repo and kicked a rerun. 

image

**Comment by hoffie** [comment]
>  Set the permissions to more restrictive on this repo and kicked a rerun.

You did that for jamulussoftware/jamulus, right?
The latest run on this PR was identical, JACK still works. So it seems good to me.

Also, I think that setting should not matter for two reasons:
- It only defines defaults while our autobuild workflow sets specific values and should therefore not be affected by defaults.
- The build did not fail in a git-related operation (and the setting should only be related to git permissions, not filesystem permissions or anything else).

**Comment by ann0see** [comment]
> You did that for jamulussoftware/jamulus, right?

Yes 

> Also, I think that setting should not matter for two reasons (good to have it tested nevertheless, though!)

I think so too. Maybe the reason is something else. But it could be some concurrency issue - which you fix here.

**Review by pljones — APPROVED** [review]

**Review by ann0see — APPROVED** [review]

**Comment by ann0see** [comment]
Thanks!

**Pull request merged**
