### PR TITLE
Add Delay Pan Server Setting to server ini

### LINKED ISSUE #1743: Server: Delay panning status is not saved
> It seems, that in server mode the 'delay pan' option is not stored in the 'ini'. I observed this on Windows 7 and on an Ubuntu based system.

_Originally posted by @DetlefHennings in https://github.com/jamulussoftware/jamulus/discussions/1707#discussioncomment-771881_

### PR DESCRIPTION
**Pull request by henkdegroot**
Fixes #1743

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
Thanks!
Looks good to me and works as expected.

Note: I initially thought that logic for updating the checkbox would be missing, but this is covered by the existing code (i.e. starting with `--delaypan` will enable delay panning and check the checkbox).

**This PR should only be merged once we've decided when to do it as summarized here: https://github.com/jamulussoftware/jamulus/issues/1743#issuecomment-846449224**

**Review by pljones — APPROVED** [review]

**Comment by pljones** [comment]
Just to repeat...
**This PR should only be merged once we've decided when to do it as summarized here: https://github.com/jamulussoftware/jamulus/issues/1743#issuecomment-846449224**

**Comment by henkdegroot** [comment]
While this option (PR) is doing what it supposed to do, perhaps we should look at adding extra logic?

Currently this setting can be enabled using the command-line option and a GUI tickbox.
For me it makes sense, that when you enable this in the GUI to store this setting in the ini.
But does it also make sense to store the setting if it was activated by command-line?

**Comment by pljones** [comment]
There was a long discussion on that.  Volker was adamant that command line options for the server should not affect the inifile.

(I had a branch completely rewriting the settings and inifile handling.)

**Comment by ann0see** [comment]
Ok. So what’s the agreement? Should we merge this one?

**Comment by ann0see** [comment]
Merging since we're going to need a rc2 anyway.

**Pull request merged**
