### PR TITLE
Update sk_SK app translation for 3.8.2

### LINKED ISSUE #2309: Update sk_SK app translation for 3.8.2
Hi @jose1711,
We are getting ready for the 3.8.2 release. No further changes to translatable strings are currently planned for this release.

We would be happy if you updated the Jamulus software translations for **sk_SK** by **2022-02-06**.

Please
- Update your fork from `jamulussoftware/jamulus` `master` and create a working branch
- Update translations using Qt Linguist in your fork,
- Commit and push your changes and reference this Issue,
- Open a Pull Request before 2022-02-06

Suggested commit and PR message:
```
Update sk_SK app translation for 3.8.2

Fixes #2309
```

Note: Some of the displayed "untranslated" strings will actually not be new, but will rather be shown due to technical reformatting (e.g. %1). You may be able to easily update them using the "vanished" translations list.

Further documentation can be found in [TRANSLATING.md](https://github.com/jamulussoftware/jamulus/blob/master/TRANSLATING.md).

Thanks for contributing to Jamulus!

### PR DESCRIPTION
**Pull request by jose1711**
Fixes #2309

### CODE REVIEW

**Comment by ann0see** [comment]
Great. Thank you very much!

**Review by ann0see — APPROVED** [review]
Looks good. Disclaimer: I only scanned the text.

**Review by hoffie — APPROVED** [review]
Looks good to me, thanks a lot for your work!

Note:
- Looks like not all strings are translated. The missing ones mainly seem to be *What's this* texts. If you plan to update this PR with more translations, please let us know. If you don't plan to, that's fine as well. I guess we'll merge this tomorrow.
- It looks like there's currently no Windows installer translations for sk (src/res/translation/wininstaller/). If you want, you could add those as well. Those work differently. Just let us know if you want to work on this and we should be able to provide you with guidance. :)


- [x] Translator listed in the src/util.cpp, optionally add link to PR or code
- [x] Punctuation and spacing consistent.
- [x] Signal words consistent (“ASIO”, “Buffer”)
- [ ] *App translations: No untranslated strings (grep unfinished -5 src/res/translation/translation_$TRANSLATION*.ts)*
- [x] App translations: Only a single .ts file checked in (.qm in addition is also OK)
- [ ] Installer translations: No translations

Approving, but **waiting with the merge** until tomorrow for possible feedback.

**Comment by jose1711** [comment]
> Looks good to me, thanks a lot for your work!

Thank you.

> Note:
> 
>     * Looks like not all strings are translated. The missing ones mainly seem to be _What's this_ texts. If you plan to update this PR with more translations, please let us know. If you don't plan to, that's fine as well. I guess we'll merge this tomorrow.

Not planning to add the missing ones in the near future.

>     * It looks like there's currently no Windows installer translations for sk (src/res/translation/wininstaller/). If you want, you could add those as well. Those work differently. Just let us know if you want to work on this and we should be able to provide you with guidance. :)

Thank you for the heads up, I am using solely Linux on all my machines so the motivation is simply lacking.

**Comment by hoffie** [comment]
Thanks for the feedback. Understandable :)

**Pull request merged**
