### PR TITLE
Reorder settings

### PR DESCRIPTION
**Pull request by pljones**
**Short description of changes**

Does nothing.  Well, it moves things around in settings.cpp so they're in a more... controlled... order.

**Status of this Pull Request**

Been running locally happily enough.

**What is missing until this pull request can be merged?**

Should be good to go.  Wants a squash merge.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Comment by pljones** [comment]
After this one,
* patch/ocd-reorder-of-serverdlg-bits
Similarly does very little - concentrating on the server dialog, though

* feature/server-list-persistence-ui
Where these bits have been leading.  There's a build workflow currently sitting here:
https://github.com/pljones/jamulus/actions/runs/1593461010
with the artifacts for the head of that branch (which is what I run locally)

**Review by softins — APPROVED** [review]
Compiles for me and the ini file is still correct after running. Looks good.

**Comment by pljones** [comment]
@ann0see OK if I merge?

**Review by ann0see — APPROVED** [review]
Looks ok.

**Pull request merged**
