### PR TITLE
Create KR translation for Windows installer

### PR DESCRIPTION
**Pull request by bagjunggyu**
This is for creating an translation file for Korean in installer.

### CODE REVIEW

**Comment by bagjunggyu** [comment]
Well, I can't find any issue for this merging though,
If it would be failed again, I should find other way.

**Comment by ann0see** [comment]
You need to edit the file on The branch you‘ve raised this Pull request (short form: PR or MR) from.

I‘d suggest to read  https://www.freecodecamp.org/news/what-is-git-and-how-to-use-it-c341b049ae61/

and https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md to get a bit used to GitHub and git since it can get really confusing at the beginning of you start participating in an open source project.

**Comment by bagjunggyu** [comment]
OK! all checks have passed now it just need 2 review.
two Jamulus member can review this.

**Comment by ann0see** [comment]
Yes. But it won't show up. You still need the other file to be changed

**Comment by bagjunggyu** [comment]
I think it can be done after 2 reviews and merging next PR 
https://github.com/jamulussoftware/jamulus/pull/2670

**Comment by ann0see** [comment]
It should happen in one PR to allow testing. 

You should be able to use the following link to edit the mentioned file and it should show up here.

https://github.com/bagjunggyu/jamulus/blob/master/src/translation/wininstaller/installerlng.nsi

**Comment by bagjunggyu** [comment]
OK, Thanks.
now, I did it.

**Comment by ann0see** [comment]
Could you please test if the translation shows up correctly? You can get the installer from the "Checks" tab on this PR. You should find the "artifacts" on the bottom of that page which are the built versions of Jamulus including your changes.

Afterwards uninstall Jamulus manually and install it again via your downloaded installer. You need to uninstall it first to be able to change the language during setup. 

Please take some screenshots of the pages and check if the layout is ok.

**Comment by bagjunggyu** [comment]
wow! this is strange though, anyway it worked :)
I can see the Korean in installer.
IMG_2216

**Comment by ann0see** [comment]
Looks good. What’s strange? The ASIO warning? Maybe that’s a bug although I‘ve never seen it occur if an ASIO Driver was installed. 

But back on topic: would you like to be mentioned as translator in the app?

**Comment by ann0see** [comment]
@BLumia Do you know Korean?

**Comment by BLumia** [comment]
> @BLumia Do you know Korean?

Sorry I don't know Korean 😂

**Comment by chanjin65** [comment]
I am a Korean. How can I help you?


2022년 6월 26일 (일) 오후 7:26, ann0see ***@***.***>님이 작성:

**Comment by ann0see** [comment]
@BLumia Good to know. It would be good to have a reviewer/proof/partner reader for Korean to spot mistakes/give tips/can be asked. Would you (@chanjin65) mind reviewing this Pull Request with @bagjunggyu

**Comment by bagjunggyu** [comment]
Since, It doesn't seem to be merged yet. but, it worked :) 
Anyway, thank you for about mentioning me as a translator in the app.

**Comment by ann0see** [comment]
Yes, merging might take a bit (we're not that efficient in bringing PRs in quickly.) I'm quite sure that it'll be merged in the coming days.

**Review by hoffie — APPROVED** [review]
Looks good to me code-wise.
- [ ] Translator listed in the `src/util.cpp`: Can be added by a maintainer before merge (not doing it now to avoid further git work ;))
- [x] Punctuation and spacing consistent (as far as I can tell...)
- [x] Signal words consistent ("ASIO", "Buffer")
- [x] Installer translations: Passes `tools/check-wininstaller-translations.sh`

Thanks @bagjunggyu!

**Comment by ann0see** [comment]
@hoffie @pljones somehow the Changelog didn't get the full entry.

**Pull request merged**
