### PR TITLE
Fix some bugs in jam exporter

### PR DESCRIPTION
**Pull request by pljones**
Version bump for jam exporter

### CODE REVIEW

**Review by ann0see — APPROVED** [review]
I don’t think I need to test this ;-)

**Review by ann0see — APPROVED** [review]

**Comment by softins** [comment]
Just want to understand what I'm being asked to review here? Peter's changes in his own project? Or just the fact that the update has happened? What is the actual content of this PR, and the reason for raising it?

I have two projects listed in tools too: jamulus-php and jamulus-web. Should I raise some kind of PR here when I make changes within those projects? If so, I didn't know that before.

**Comment by ann0see** [comment]
> Just want to understand what I'm being asked to review here?

Currently, PRs can/should only be merged if two people with write access to this repo have approved it. I assume (since these two projects are from Peter), that we can merge it although I haven't tested the code. Somebody else needs to approve this PR in order to get it merged.

**Comment by softins** [comment]
> > Just want to understand what I'm being asked to review here?
> 
> Currently, PRs can/should only be merged if two people with write access to this repo have approved it. I assume (since these two projects are from Peter), that we can merge it although I haven't tested the code. Somebody else needs to approve this PR in order to get it merged.
> 
> I hope this clarifies the review request ;-).

I understand the review policy. What I don't understand is the purpose of this PR. The two files changed are not within the jamulus repo, but within Peter's own project. I wasn't aware that changes to sub-projects (as I said, I have two) required a PR in the "parent" project. I though that the sub-projects were just external references to other independent repos. In my working directory, all the sub-directories within `tools/` are empty. Although a `git diff` does seem to show up a change in a commit ID:

```
tony@pi:~/jamulus-pljones $ git checkout bugfix/jamexporter-had-bugs
Branch 'bugfix/jamexporter-had-bugs' set up to track remote branch 'bugfix/jamexporter-had-bugs' from 'origin'.
Switched to a new branch 'bugfix/jamexporter-had-bugs'
tony@pi:~/jamulus-pljones $ git diff ..master
diff --git a/tools/jamulus-jamexporter b/tools/jamulus-jamexporter
index f89fece1..aad00120 160000
--- a/tools/jamulus-jamexporter
+++ b/tools/jamulus-jamexporter
@@ -1 +1 @@
-Subproject commit f89fece13d9483a19406a72f27ce5095e5e16a2b
+Subproject commit aad00120143448134ac51f4bc07fb6e874744395
```

I'm happy to approve it, it's just highlighted something that I don't yet understand within Github.

**Review by softins — APPROVED** [review]

**Comment by ann0see** [comment]
I think only @pljones can comment on that b

**Comment by pljones** [comment]
It's the way git modules work.  The Jamulus git project has other git projects defined as modules - with explicit commit ids as the "mount points" into the Jamulus project.  If the Jamulus project wants to take a newer version of one of the modules, it needs that module's version to be "remounted" at the correct point in time.

**Pull request merged**
