### PR TITLE
Display server version after name in mixer board

### PR DESCRIPTION
**Pull request by softins**
Add the version of the connected server after its name in the title of the Audio Mixer Board

**Context: Fixes an issue?**

Some issues are dependent on the version of the server the client is connected to. See for example the discussion at https://github.com/jamulussoftware/jamulus/issues/1935#issuecomment-893483589. At the moment, it is necessary to check [Jamulus Explorer](https://explorer.jamulus.io) to determine the version of a server. With this change, the version will be displayed after the server name in the client window, making diagnosis of issues easier. It might also encourage server operators to update their versions.

**Does this change need documentation? What needs to be documented and how?**

Documentation not really critical, as it should be self-explanatory. Servers before 3.5.5 will be shown as `<3.5.5`, as that is the first version that sends its version number to the client.

**Status of this Pull Request**

Working implementation.

**What is missing until this pull request can be merged?**

Should be ready.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Comment by pljones** [comment]
image
I think the mixer title is already a bit over-crowded, especially when recording is active.  I'd rather have it in the window title bar, if that's feasible (i.e. works cross-platform reliably).

**Comment by softins** [comment]
> image
> I think the mixer title is already a bit over-crowded, especially when recording is active. I'd rather have it in the window title bar, if that's feasible (i.e. works cross-platform reliably).
> 
> And yes, there's already more going on in the window title... I guess it's that I feel the mixer title should be that - saying "this is the mix at the server you're connected to" and nothing else. I didn't like putting the recording active there, really... The window title is describing the server (i.e. name, how many users). Adding the version there just feels more in context.

I disagree. I think users are going to be more aware of what is displayed in the mixer title than the window title (I certainly am). It is also the same on each platform then. I would support replacing `[RECORDING ACTIVE]` with just `[RECORDING]`, but that's a different issue.

> It would also be a much smaller change... :)

Really? This PR isn't really a big change anyway. Most of it would be needed the same whether putting it in the window title or the mixer title.

But either way, it's worth displaying the server version in principle, yes?

**Comment by pljones** [comment]
> But either way, it's worth displaying the server version in principle, yes?

Oh yes.  And I was thinking if it's in the title bar, adding the client version after "Jamulus" would also make sense.  Then getting a report from a user could ask for the full title bar text.

**Comment by softins** [comment]
> > But either way, it's worth displaying the server version in principle, yes?
> 
> 
> 
> Oh yes.  And I was thinking if it's in the title bar, adding the client version after "Jamulus" would also make sense.  Then getting a report from a user could ask for the full title bar text.

I don't really think we need to put the client version on display all the time. For most people, who aren't developers, the client version will only change when they install a new version. And it is easily available already via About Jamulus.

The server version, in contrast, changes depending on where you connect to.

I still prefer putting the server version in the mixer title rather than the window title.

**Comment by pljones** [comment]
I'd question then why the number of users is in the window title - it's to do with the server you're connected to and changes more than the server version does.

**Comment by softins** [comment]
> I'd question then why the number of users is in the window title - it's to do with the server you're connected to and changes more than the server version does.

Maybe, but I never look at it.

**Comment by gilgongo** [comment]
While I realise the client version is also in the Help panel, I think contrasting the client version with the server version helps disambiguate what's being referred to (given the possible confusion in showing a version number in the client that relates to the server). So I'd go for having it in the title bar as "ServerName (v3.6.1) - 7 users - Jamulus (v3.8.2)" as we have the space there. We could of course (also?) put it in the Help, but that does seem a bit hidden away. 

Also agree with @pljones that the best we can hope for is to use this as a diagnostic. I doubt many people would notice it proactively, as it were.

That said, might we be cheeky and for servers before 3.5.5 show that as `(legacy)`?

**Comment by softins** [comment]
> While I realise the client version is also in the Help panel, I think contrasting the client version with the server version helps disambiguate what's being referred to (given the possible confusion in showing a version number in the client that relates to the server). So I'd go for having it in the title bar as "ServerName (v3.6.1) - 7 users - Jamulus (v3.8.2)" as we have the space there.

I don't like that at all, it makes it far too cluttered. The Help About is fine for getting the client version number when needed. I think the server name was added to the title bar to help those running multiple clients connected to different servers (e.g. WorldJam people).

> We could of course (also?) put it in the Help, but that does seem a bit hidden away.

If you mean the version of the connected server, that doesn't belong in the Help, as it isn't about the client.

> Also agree with @pljones that the best we can hope for is to use this as a diagnostic. I doubt many people would notice it proactively, as it were.

I still feel strongly that the better place for the server version is immediately after the server name in the mixer title, as that is the context of "where you are connected to" that people would notice most.

But I haven't got the energy to keep arguing about it, so am tempted just to close the PR.

> That said, might we be cheeky and for servers before 3.5.5 show that as `(legacy)`?

I wondered about something like that or "(VERY OLD)", but decided against it as it is a value judgement and would also require translation. So I settled on the neutral and factual "(<3.5.5)".

**Comment by gilgongo** [comment]
> I don't like that at all, it makes it far too cluttered.

You just said you don't look at it :-)

**Comment by gilgongo** [comment]
I don't have a problem with it being in the mixer panel, it was only that if we wanted to put it in the title, we'd need to disambiguate the server version fromt the client version (since the convention with a version number there is that it would refer to the client).

**Comment by pljones** [comment]
There's too much on the mixer title bar already for my tastes.

So it's a matter of taste and preference, here, by the sound of it.

There's no technical reason to do one thing rather than the other.

At which point it raises the question: what problem is it solving:
>  With this change, the version will be displayed after the server name in the client window, making diagnosis of issues easier.

And that doesn't provide guidance on which to prefer, either.

**Comment by gilgongo** [comment]
I don't think it's completely either/or, hence my point about the need to pair the client version with the server one if we put it in the title bar. I think we could have just the server version if you put it in the mixer panel.

**Pull request closed without merging**
