### PR TITLE
Android update replacing PR #1528

### PR DESCRIPTION
**Pull request by softins**
**Short description of changes**

Rebased and squashed version of @j-santander PR #1528, with a few additional corrections.

**Context: Fixes an issue?**

The original PR #1528 has been waiting for some months, but it was based on the submitter's `master` branch. Rather than pushing updates to his `master`, I created a new branch in my own repo. Can close #1528.

**Does this change need documentation? What needs to be documented and how?**

No

**Status of this Pull Request**

Built successfully on Ubuntu20 and tried out on my Android phone. Looks ok.

**What is missing until this pull request can be merged?**

Ready to merge, although the Android port needs more work in general.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Not tested yet,..

**Comment by ann0see** [comment]
Not quite sure if it's a problem with the windows 11 subsystem for android, but I couldn't hear any sound. But to be honest, it's not the way to correctly test the app ;-).

**Comment by softins** [comment]
> Not quite sure if it's a problem with the windows 11 subsystem for android, but I couldn't hear any sound. But to be honest, it's not the way to correctly test the app ;-). Also it seems to be unstable. But I'd say that's expected for beta software.

Was fine on my phone just now. Listened to a session for a while. Little bit of bubbling in the sound, but that could easily have been my wifi or one of the participants.

**Comment by ann0see** [comment]
Hmm. Probably gonna approve it then.

**Review by ann0see — APPROVED** [review]

**Pull request merged**
