### PR TITLE
Global MsgBoxes and Commandline

### PR DESCRIPTION
**Pull request by pgScorpio**
**Short description of changes**

New attempt replacing #2541

Added global messagebox and commandline parameter parsing classes to global.h/main.c
Adapted all messageboxes to use the new CMsgBoxes class.

CHANGELOG: 

**Context: Fixes an issue?**

General improvement and preparation for sound-redesign.

**Does this change need documentation? What needs to be documented and how?**

**Status of this Pull Request**

**What is missing until this pull request can be merged?**

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Thanks. If you want, we can use this PR as "learning PR" on Friday?

**Comment by pgScorpio** [comment]
> Thanks. If you want, we can use this PR as "learning PR" on Friday?

Well, if we are going to experiment, I prefer not to do that on any of my working branches, but of coarse we always can create a temporary branch to do so.

**Comment by ann0see** [comment]
> Well, if we are going to experiment, I prefer not to do that on any of my working branches

Yes sure. But we might also want to touch this one. But let's wait what tomorrow brings ;-)


BTW: Congrats the coding style now worked ;-)

**Comment by hoffie** [comment]
Should this PR be closed in favor of #2598?

**Comment by pgScorpio** [comment]
> Should this PR be closed in favor of #2598?

You're right!

This PR is replaced by #2598 and #2599

**Pull request closed without merging**
