### PR TITLE
Update FR app translation for 3.8.0

### PR DESCRIPTION
**Pull request by jujudusud**
Adding more translation update in RC2 stage.

### CODE REVIEW

**Comment by hoffie** [comment]
Thanks. From a quick look at the diff, this "just" cleans up the .ts file (which is good!), but does not change any visible translations, right?
If this is the case, I suggest merging it post-3.8.0 to avoid all unnecessary changes?

**Review by hoffie — APPROVED** [review]
Just saw that one word changes: "Jitter". Let's wait what the others say wrt. right time to merge.

**Comment by jujudusud** [comment]
It is the latest translations needed by the new arrangement of the main window (jitter added and removed from parameters).
If the modifications of the jitter is merged, then the translation have also to be merged. If not, the translation will not be complete.

**Comment by hoffie** [comment]
Changed milestone to 3.8.0 as this PR avoids a visible missing translation.

**Review by ann0see — APPROVED** [review]
Merging this since I think it’s small

**Pull request merged**
