### PR TITLE
CI: Run shellcheck & shfmt on PRs & branches

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**
Run shellcheck & shfmt on PRs & branches

- Uses least privilege approach and does not rely on external actions.
- Runs on all pushes or pull requests which touch .sh files. Can also be run manually.

Example run:
https://github.com/hoffie/jamulus/runs/6716242088?check_suite_focus=true

CHANGELOG: Scripts: Coding style and static checks for shell scripts are now enforced.

**Context: Fixes an issue?**
Related: #2474

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Ready.

**What is missing until this pull request can be merged?**

Reviews.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Any advantages/disadvantages to put this into the clang format run?

**Comment by hoffie** [comment]
Do you mean combining the workflows?
That would be possible, but I don't think we could restrict this workflow to just shell files in that case (meaning that it will always run, something which we are trying to reduce...? :)).

**Comment by ann0see** [comment]
Spinning up a runner also costs. Maybe even more?

**Comment by pljones** [comment]
Does anyone _manually_ run the clang-format check?  Would they be expecting it to start worrying about scripts?

Conversely, would anyone want to _only_ run the script check without the full clang-format check?

Given how quick running "make clang_format" is, I'd expect spinning up the builder to be the most expensive part of the process in terms of elapse time, if nothing else.  On the whole, I'm tending towards just bundling it all together.  I'd keep separate "make" options, though.

**Comment by ann0see** [comment]
Yeah. Probably putting it together is cleaner and sustainable?

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
@hoffie I think we should put it into the clang format file and run it only if there are changes to cpp, mm, sh, h, ... files.

**Review by ann0see — APPROVED** [review]

**Pull request merged**
