### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Jamulus/Jamulus app](https://hosted.weblate.org/projects/jamulus/jamulus-app/).

It also includes following components:

* [Jamulus/Windows Installer](https://hosted.weblate.org/projects/jamulus/windows-installer/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Review by hoffie — APPROVED** [review]

**Comment by ann0see** [comment]
@yangyangdaji thanks for the change. @hoffie I'm not sure if we use Sie or du in the app (probably we use both). The website uses "du", so probably we should be consistent in the app too?

**Comment by hoffie** [comment]
> @yangyangdaji thanks for the change. @hoffie I'm not sure if we use Sie or du in the app (probably we use both). The website uses "du", so probably we should be consistent in the app too?

I think we strive to avoid it:
```
$ grep -P '\bSie\b' src/translation/translation_de_DE.ts  | grep -v vanished | wc -l
6
$ grep -P '\bDu\b' src/translation/translation_de_DE.ts  | grep -v vanished | wc -l
9
```

(BTW: I had approved this PR before Weblate added more commits)

**Comment by ann0see** [comment]
Hmm. I thought so... Maybe do the following: 
1. Try to avoid it 
2. if needed use "du" like on the website.

**Comment by ignotus666** [comment]
Something went wrong here. Weblate says:

> ERROR: Repository not found.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

Could there be an issue with the webhook or something?

**Comment by ignotus666** [comment]
Nope, the guys at Weblate finally deleted the fork based on my repo... I hope what's been done on weblate doesn't get lost.

**Comment by yangyangdaji** [comment]
You can use patch files https://patch-diff.githubusercontent.com/raw/jamulussoftware/jamulus/pull/2921.patch

**Comment by ignotus666** [comment]
Not sure how to use that - but there are many more updates anyway.

**Comment by yangyangdaji** [comment]
see https://www.gitkraken.com/learn/git/git-patch#Git-Patch-Apply

**Comment by ignotus666** [comment]
Ok, I can download the updated files from weblate, create a PR myself with those and the patch file, delete the component and re-create it. And hope that works.

**Comment by ignotus666** [comment]
Done. Until #2922 is merged we can't test whether it worked. Hopefully it does and forks from the correct repo.

**Review by ann0see — APPROVED** [review]
@ignotus666 I think I can even merge this one!

**Pull request merged**
