### PR TITLE
Scripts: Set -o pipefail

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**
This is supposed to avoid silent failures when using pipes.
Example: #2793 (https://github.com/hoffie/jamulus/runs/7930874876?check_suite_focus=true#step:9:42)

CHANGELOG: Internal: Hardened build scripts and tooling against silent failures.

**Context: Fixes an issue?**

**Does this change need documentation? What needs to be documented and how?**
No.

**Status of this Pull Request**

**What is missing until this pull request can be merged?**
- [x] CI green
- [x] tools/ needs explicit review/testing for pipe usage.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by hoffie** [comment]
Testable tooling (e.g. translation checker, copyright updates) tested. All scripts reviewed for potential unwanted side effects (little pipe usage and where pipes are used, they should be checked properly).

The Linux CI failure is expected and is a proof of this change working properly. It will go once #2793 is merged and the PR is rebased.

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
I think you should now rebase this PR?

**Comment by hoffie** [comment]
Rebased. Linux builds are green now as well, as expected.

**Review by ann0see — APPROVED** [review]

**Comment by pljones** [comment]
I had to do this:
https://github.com/jamulussoftware/jamulus/commit/b333de3ec047d7f4768fc0151990d6155fd36924
I'd guess the "pipefail" change meant I now got a silent failure - rather than preventing one, it caused it.  `|| true` ignores the fail...  Just a hack to get the script working for now.

**Pull request merged**
