### PR TITLE
Autobuild: Mac: Build with Qt 6.3.1

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

This will start building with the latest version of macOS on the latest available SDK.
Related to: https://github.com/jamulussoftware/jamulus/pull/2300

CHANGELOG: Build: macOS will now be built with Qt 6.3.1 for better support of modern versions of macOS. Users of macOS 10.14 or earlier must from now use the legacy build or compile from source.

**Context: Fixes an issue?**

Mostly GUI related issues, but it has the potential of fixing a few macOS related issues as mentioned in https://github.com/jamulussoftware/jamulus/pull/2300

**Does this change need documentation? What needs to be documented and how?**

Yes. We need to tell macOS users that they might need to use the legacy version. 

**Status of this Pull Request**

Final test on macOS. Will do as soon as the build is finished.
I used the latest SDK, but we can also use SDK 11 with Xcode 12 if that adds more compatibility

**What is missing until this pull request can be merged?**

Review and test. @emlynmac could you please test the artifacts?

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
macOS Catalina client and server work. Sound is ok (quicly tested over WiFi). GUI seems to be ok too. MacOS Monteray on a VM seems to work too (didn't test sound, but since it works on Catalina, it should be OK)

**Comment by hoffie** [comment]
> As expected, the country and language are copied from a Qt 5.15.2 build.

@ann0see, you mean that language settings work the same as after any other Jamulus update and there's no need for manual intervention, right?

**Review by hoffie — APPROVED** [review]

**Comment by emlynmac** [comment]
@ann0see I've taken your branch and pushed to my repo to test the full auto build with signing.

**Comment by ann0see** [comment]
> You mean that language settings work the same as after any other Jamulus update and there's no need for manual intervention, right?

Yes.

**Comment by emlynmac** [comment]
Signed build available here: https://github.com/emlynmac/jamulus/suites/7114281518/artifacts/282026065

**Comment by ann0see** [comment]
Just tested the signed build on a VM and it installed ok. So everything seems work as expected?

**Comment by ann0see** [comment]
Ok. Fingers crossed...

**Comment by hoffie** [comment]
CI now logs a [lack of `aqt` support for this version](https://github.com/jamulussoftware/jamulus/runs/7101459315?check_suite_focus=true#step:7:117). I guess it's just cosmetical, but mentioning here anyway.

**Comment by ann0see** [comment]
I've now documented that the legacy version now should be used on Mojave or earlier: https://github.com/jamulussoftware/jamuluswebsite/commit/e13d875fca0b3b3751315b40d836272db6c2e37f

**Comment by pljones** [comment]
> I've now documented that the legacy version now should be used on Mojave or earlier: [jamulussoftware/jamuluswebsite@e13d875](https://github.com/jamulussoftware/jamuluswebsite/commit/e13d875fca0b3b3751315b40d836272db6c2e37f)

Once that's merged, the "needs documentation" label here should be removed, right?

**Comment by ann0see** [comment]
Yes, if we don't have anything else. Probably the release announcement needs it mentioned.

**Comment by ann0see** [comment]
Probably yes? I'll remove the needs documentation tag.

**Pull request merged**
