### PR TITLE
i18n(installer): add zh_CN translation for nsis win installer

### PR DESCRIPTION
**Pull request by BLumia**
**Short description of changes**

SimpChinese translation for Windows installer.

**Context: Fixes an issue?**

No

**Does this change need documentation? What needs to be documented and how?**

No?

**Status of this Pull Request**

**What is missing until this pull request can be merged?**

- [x] Wait for CI build and test it locally.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Comment by BLumia** [comment]
image

image

Tested it on my machine and works fine. Note if you also would like to test it out but already installed it via the installer before, you need to delete the `InstallLanguage` key under registry path `HKLM\Software\Jamulus` first.

**Review by ann0see — COMMENTED** [review]
Thanks again. Looks good to me.

Can’t say much about the Chinese unfortunately. 

Will go through the review checklist as soon as I find enough time. 

Note to other maintainers: @BLumia has not been added to the chat and the translators role yet. This should be done

**Review by ann0see — APPROVED** [review]
- [ ] Translator listed in the `src/util.cpp` (no. But see https://github.com/jamulussoftware/jamulus/pull/1927)
- [x] Looks consistent
- [x] Passes `tools/check-wininstaller-translations.sh` @hoffie: the script might need an update since zh_cn does not fit https://github.com/jamulussoftware/jamulus/blob/417a9bc8c26cdf06fb301cdfaa96e3f875a52666/tools/check-wininstaller-translations.sh#L9

**Comment by ann0see** [comment]
Should be merged after my PR and the other one by @BLumia

**Comment by gilgongo** [comment]
OK I've merged #1927 - just need to update src/util.cpp on this and will do the same here.

**Comment by BLumia** [comment]
> just need to update src/util.cpp on this and will do the same here.

I'm confused. Since #1927 is merged, what needs to be added to `src/util.cpp` for this patchset?

**Comment by ann0see** [comment]
Probably you need to add yourself as contributor and translator?

**Comment by BLumia** [comment]
> Probably you need to add yourself as contributor and translator?

Not sure since most of the work is translating, anyway added it in 758e5f1 and also rebased my patchset onto the current master branch now :)

**Comment by ann0see** [comment]
Thanks ;-).
@gilgongo is this one ready now?

**Comment by gilgongo** [comment]
OK great! Thanks for all your effort on this @BLumia

**Pull request merged**
