### PR TITLE
Fix for #1451 - unicode in mixer should wrap on character boundaries (take 2)

### PR DESCRIPTION
**Pull request by pljones**
**Short description of changes**

@djfun wrote a fix but didn't raise a PR, so here's the PR.

**Context: Fixes an issue?**

Yes.  #1688.  This still happens.

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Needs testing.

**What is missing until this pull request can be merged?**

Needs testing.

## Checklist
- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [ ] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

----

I've now created a branch off jamulussoftware/jamulus master and merged @djfun's changes to that, then fixed the conflicts.

I'll try it out now.

### CODE REVIEW

**Comment by pljones** [comment]
@jamulussoftware/maindevelopers I can't approve this as I raised the PR.

**Comment by ann0see** [comment]
Currently don’t have time testing/helping out much, but happy to approve. (my studies are challenging – especially dynamic programming is hard 😀).

Would it be worth to elect another main-dev (Ignotus,DonC,corrados (?),…)?

**Review by ann0see — APPROVED** [review]
Untested

**Comment by softins** [comment]
> Would it be worth to elect another main-dev (Ignotus,DonC,corrados (?),…)?

Or maybe dtinth?

**Comment by ann0see** [comment]
Depends on who wants/finds the time and fits the team.

I‘d like to see corrados back 😀 but definitely dtinth is another good idea. 

So the new person would do 
* maintenance:
* testing/reviewing PRs (—> the person should have at least basic coding experience)
* Get write access to all GitHub repos (—> the person should be trustworthy)
* moderate the Community and encourage positive behaviour (—> the person should be social)
* should follow https://opensource.guide/best-practices/
* 

Maybe we should move this to a discussion

**Pull request merged**
