### PR TITLE
Highlite the fact the server is recording

### PR DESCRIPTION
**Pull request by dcorson-ticino-com**
Highlite the fact the server is recording by making the MixerBoard title white on a red background.

New function in clientdlg SetMixerBoardDeco sets MixerBoard title formatting depending on recorder state
and skin, called by recorder state change, skin change and disconnect.

### CODE REVIEW

**Comment by ann0see** [comment]
Hmm. Something seems to be wrong about this commit/pr (it changes a few other files). For me it looks like you might need to rebase your repo and re-apply the changes.

**Review by ann0see — CHANGES_REQUESTED** [review]
Hmm. Something seems to be wrong about this commit/pr (it changes a few other files). For me it looks like you might need to rebase your repo and re-apply the changes.

**Comment by dcorson-ticino-com** [comment]
Hi ann0see, can you give me or point me to a step-by-step that works please ?
Git has me totally confused, I have used different CVS systems before, but I am lost with git for the moment.
Googling finds discussions what could maybe work and no solutions.
Actually I tried yesterday to do exactly what you said.  Start with a new repo and add my changes to that.
No problem to do that again, it is not much to change.
But how.
Don

**Comment by ann0see** [comment]
I think you might need to create a new branch on your repo which is up to date with the master branch here, add your changes and then open a PR.

So you'd add a new git remote with `git remote` to your local repo (not sure how the exact command would be at the moment), git fetch the upstream repo, git checkout a new branch, add your changes and then git push them to your repo. Afterwards you re-open a PR.

Maybe https://www.atlassian.com/git/tutorials/git-forks-and-upstreams

Somehow helps (not yet fully read it)

**Comment by pljones** [comment]
I don't think this is _really_ meant to change 47 files, right?

**Comment by dcorson-ticino-com** [comment]
No it doesn't, it changes 3.

In the meantime I have spent more than twice as much time trying to get git to work than I did making the program change. 
I am just about to give up.
Today I deleted everything to have a clean slate and I now seem to have a branch on github that is OK.
When I do a pull request it tells me there are no differences but shows the differences that are there in the 3 files correctly.
I can find no way to proceed.

Going out for a walk in the rain.

Don

**Comment by hoffie** [comment]
@dcorson-ticino-com This is sad to hear! Git can be hard to work with, sometimes. :(

Trying to find out what happened: When looking at your [feature-req925_recording_indicator branch](https://github.com/dcorson-ticino-com/jamulus/commits/feature-req925_recording_indicator), it seems like this branch contains all of Jamulus' history in its first commit and then your intended changes as a second commit.
This would also explain the behavior you are seeing -- there is a correct diff when comparing the code 1:1, but git will not be able to merge this properly as the histories are diverged.

Not sure how that can happen. What UI are you using? Github directly? The git command line? Some editor with git support?

If the latest commit (26fb47b2e182294c89a409f307c3347e5f144ee7) contains all the changes you want to propose, then the following should work for you:

``` bash
# Start fresh
$ git clone git@github.com:dcorson-ticino-com/jamulus.git jamulus2021-02-07
$ cd jamulus2021-02-07

# Ensure that you are working with the latest official Jamulus master code base
$ git remote add jamulussoftware git@github.com:jamulussoftware/jamulus.git
$ git pull --rebase jamulussoftware master

# Create a new branch for this PR
$ git checkout -b pr957-server-recording

# Re-apply the work you have already done:
$ git cherry-pick remotes/origin/feature-req925_recording_indicator
[pr957-server-recording dd8f0539] feature-req925 recording indicator
 Author: DonC <dcorson@ticino.com>
 Date: Sun Feb 7 15:42:16 2021 +0100
 3 files changed, 47 insertions(+), 5 deletions(-)

# Push your prepared branch to Github:
$ git push --set-upstream origin pr957-server-recording
```

Then open the PR by using the URL which Github returns on the command line or going to Github directly and selecting the newly created branch.

Hope this helps. In any case, keep your branches online so that the work can be saved. I'm sure this work is valuable.

**Comment by dcorson-ticino-com** [comment]
Thanks Christian,
It looks like it worked, the only complication being non-existant ssh public key.
I was using the git tools of Qt Creator.  Don't know what happened.
When that didn't work I made a second try with GitGui which is even more opaque as they seem to change some of the jargon.

At least I appear to be up and running now.

Best, Don

**Pull request closed without merging**
