### PR TITLE
Move entitlements file to mac folder

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Moves the Jamulus.entitlements file to the mac/ folder to clean up the root folder

CHANGELOG: Internal: Moved entitlements file to mac/ folder to clean up the repo root.

**Context: Fixes an issue?**
No. Clean up only.

**Does this change need documentation? What needs to be documented and how?**
No.

**Status of this Pull Request**
Should be tested by @emlynmac if it still builds correctly. Also it reminds me of the sandbox writing issue (https://developer.apple.com/forums/thread/666634)

**What is missing until this pull request can be merged?**
Needs testing - especially with a signed build.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
Code looks good, an actual signing test should be run (no signing has been tested after the autobuild refactoring either...).

**Comment by ann0see** [comment]
@emlynmac coukd you please git checkout my repo and push a signed beta/nightly with these changes?

**Comment by ann0see** [comment]
Except for the infinitly long running builds on emlyn's fork, I think this is ok.

**Comment by emlynmac** [comment]
> Except for the infinitly long running builds on emlyn's fork, I think this is ok.

So to be clear, master branch no longer builds on my fork. It is consistently hanging on the build macOS stage, so whatever changes broke the signing step, it is not in this PR.

**Comment by ann0see** [comment]
Yes. I know. I'll try to run CodeQl on the legacy build instead...

**Comment by hoffie** [comment]
> Yes. I know. I'll try to run CodeQl on the legacy build instead...

See chat -- I ran a non-CodeQL master build with signing on @emlynmac's branch and it worked: https://github.com/emlynmac/jamulus/actions/runs/2054387680

**Review by softins — APPROVED** [review]
Happy to approve, assuming it builds correctly, but need to be careful about possible merge conflicts with #2563, due to the file moving.

**Pull request merged**
