### PR TITLE
Update aqt to v2.1.0

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

Updates aqt to the latest version

CHANGELOG: Internal: Updated aqt to v2.1.0 due to reliability reasons

**Context: Fixes an issue?**

Not really, but includes @hoffie 's updated mirror list.

**Does this change need documentation? What needs to be documented and how?**

No

**Status of this Pull Request**

Ready for review

**What is missing until this pull request can be merged?**

Just an autobuild test. 

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [ ] I tested my code and it does what I want (will be done via CI)
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [ ] I've filled all the content above

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
Thanks. You beat me to it... :)

Note: CodeQL is in a state which I've never seen, but I don't think it can be related to this PR.

**Comment by pljones** [comment]
Has CodeQL got out of sync somehow?  The MacOS Legacy build ran the CodeQL check -- is that right?  Is a rebase needed?

**Comment by ann0see** [comment]
Rebased. Let's have a look what CodeQl does.

**Comment by ann0see** [comment]
>  The MacOS Legacy build ran the CodeQL check -- is that right?

Yes. That should be ok due to the signing issue we tried to fix?

**Comment by pljones** [comment]
Better :)

**Review by pljones — APPROVED** [review]

**Pull request merged**
