### PR TITLE
tools/generate_json_rpc_docs.py: Fix minor coding style issues

### PR DESCRIPTION
**Pull request by hoffie**
**Short description of changes**

- tools/generate_json_rpc_docs: Avoid re-use of built-in 'type'
- tools/generate_json_rpc_docs: Fix flake8 warnings
  Mainly docstrings and line length.

(Note: flakes8 still complains about the line length of the included markdown text. I'd keep it as-is though).
CHANGELOG: SKIP

**Context: Fixes an issue?**

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Ready.

**What is missing until this pull request can be merged?**

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Review by ann0see — COMMENTED** [review]
Can't say much about python, but approving anyway since CI is green.

**Review by ann0see — APPROVED** [review]
Thanks for the quick PR.

**Review by dtinth — APPROVED** [review]
Thanks for the improvements!

**Review by pljones — APPROVED** [review]

**Comment by ann0see** [comment]
Codacy complains again:

image


Not sure how much work we should spend on this.

**Pull request merged**
