### PR TITLE
Do not run CI on documentation changes

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Stops running the CI if the documentation changes. There is no need of running the CI on non source files. New version of #1921 I think this is a quick fix (and can be update ofc.)

CHANGELOG: Stop running Autobuild if only documentation is updated to avoid wasting computation time.

**Context: Fixes an issue?**
No. Related to https://github.com/jamulussoftware/jamulus/discussions/2282#discussioncomment-2046262

**Does this change need documentation? What needs to be documented and how?**
No

**Status of this Pull Request**
Ready for review

**What is missing until this pull request can be merged?**

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want (https://github.com/ann0see/jamulus/actions/runs/2013115499 and https://github.com/ann0see/jamulus/commits/autobuild/noRunDocs are small tests)
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
Peter‘s alternative approach might also work, but this is faster to implement.

**Review by hoffie — APPROVED** [review]
Seems safe to do.

Note: README.md is part of Jamulus.pro's DISTFILES, so I guess it's part of `make dist`, but we don't run that on CI.

`paths-ignore` doesn't work for tags per the docs, so even if we ignore too much, we should be on the safe side for releases.

The duplication is not nice, but I don't see a way around.
Doing trigger-based ignores has the advantage of being able to still run the Action manually if this logic is wrong for some reason.

**Comment by hoffie** [comment]
Maybe I'm the only one caring about `git log` cleanliness, but I'd prefer context in the commit message.
`Autobuild: Don't run on README/docs-only commits` (the current message isn't clear that it's about the auto build logic)

**Comment by softins** [comment]
Just wondering, what about `ChangeLog`? And are the other `*.md` files in the root dir going to move into `docs/` at some point?

**Comment by pljones** [comment]
> Just wondering, what about `ChangeLog`? And are the other `*.md` files in the root dir going to move into `docs/` at some point?

ChangeLog, README.md and any licence-related files should stay at root level, otherwise discovery proves more difficult.  (Particularly auto-discovery.)

**Comment by ann0see** [comment]
Probably true 😀. Not sure what the gold standard is.

**Comment by pljones** [comment]
I _think_ all the remaining top-level docs need to stay there.  
* APPLEAPPSTORE.LICENCE.WAIVER and COPYING are licence-related
* README.md is definitely needed there
* Anyone looking for COMPILING.md shouldn't have to look to far - it's a "first place of reference" for those who are doing it themselves
* SECURITY.md and CONTRIBUTING.md could perhaps move unless used by Github for "project completeness scoring" or whatever

**Comment by ann0see** [comment]
> should ChangeLog be included in the files that do not trigger a rebuild?

I excluded it for the reason that I think the Debian build uses it and it’s related to the release process

**Comment by ann0see** [comment]
> Jamulus.entitlements - no idea what this is or why it's at top level.

#2529

**Pull request merged**
