### PR TITLE
Make error messages translatable

### LINKED ISSUE #2041: Initial "no JACK connection" message has no translation
**Describe the bug**
When Jamulus is started without JACK the message appears:
image

and it is not translated

**To Reproduce**
Just launch Jamulus but without JACK and with localisation other than English

**Operating system**
Arch Linux

### Jamulus Version 3.8.1beta1dev-4b5c6aaa-dirty

**Additional context**
Seems to me like this message is invoked before `QTranslator` loads its stuff.

### PR DESCRIPTION
**Pull request by ignotus666**
**Short description of changes**

This makes the JACK, ASIO, CoreAudio and Android error messages translatable. Leaving this PR as a draft.

**Context: Fixes an issue?**

Fixes #2041 

**Does this change need documentation? What needs to be documented and how?**

**Status of this Pull Request**

**What is missing until this pull request can be merged?**

## Checklist

- [ ] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [ ] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Comment by henkdegroot** [comment]
@ignotus666, I downloaded your repo, updated the .ts files and ensured dutch translation was completed. Next I generated the .qm files and build the release. Think I completed all required steps, but the error messages are still showing in English on my windows environment. Test with the removing a previous working audio device and also trying to start jack (which fails due to invalid sample rate set). Both messages were presented in English. Does it work on linux?

**Comment by ignotus666** [comment]
Yes, it works for me on Linux... Are you sure you downloaded the correct branch?

**Comment by henkdegroot** [comment]
> correct branch?

I downloaded the JACK-Err-Msgs branch. Also checked to see the updates are included, and they are (otherwise the .ts files would also not have updated). It might be something caused by Qt 5 not being aware of nl (dutch) language and therefore not defaulting to the correct language.

**Comment by ignotus666** [comment]
No idea... There's no rush anyway. I'll set up a Windows vm at some point and test it there.

**Comment by ignotus666** [comment]
Turns out some messages get translated in Linux and others don't, while none do in Windows (can't check the others). Out of my depth here so closing...

**Pull request closed without merging**
