### PR TITLE
Improve Markdown styling

### PR DESCRIPTION
**Pull request by ann0see**
This is done to (hopefully) silence some Codacy errors

**Short description of changes**
* Applies suggestions from https://codebeautify.org/markdown-formatter to our .md files. 
* Updates some outdated links

Edit: I think Codacy is very picky on .md files - we should probably ignore warnings from it. However, it is still good to have a consistent style

CHANGELOG: Internal: Applied standard style to .md files

**Context: Fixes an issue?**
No. 

**Does this change need documentation? What needs to be documented and how?**
No. 

**Status of this Pull Request**
Ready for review. Probably also for merge

**What is missing until this pull request can be merged?**
Nothing. 

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Review by pljones — APPROVED** [review]
Blimey...

**Comment by ann0see** [comment]
Should be merged before https://github.com/jamulussoftware/jamulus/issues/2553 is handled

**Review by hoffie — APPROVED** [review]
Yet another thing to check on PRs? :/

**Comment by ann0see** [comment]
In theory yes. But I don’t think it is worth it

**Pull request merged**
