### PR TITLE
smoother surface for the fancy background

### PR DESCRIPTION
**Pull request by passing**
solves https://github.com/jamulussoftware/jamulus/issues/970

### CODE REVIEW

**Comment by ann0see** [comment]
Thanks for your first PR! @jamulussoftware/designers I think that's something for you.

**Review by ann0see — APPROVED** [review]
Looks great to me. Could you please also add an entry in the ChangeLog file and your name to the contributors file in the Jamulus software?

See this commit: https://github.com/jamulussoftware/jamulus/commit/b2a09f40792df410dbc4f0a502d1c12e7f27235b#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26

**Comment by ann0see** [comment]
Great! Thanks.

**Comment by passing** [comment]
@ann0see I have updated changelog and contributors list

> Thanks for your first PR! @jamulussoftware/designers I think that's something for you.

Unfortunately, I cannot open that link, it just gives me a 404 :man_shrugging:

**Comment by ann0see** [comment]
Strange. For me it works

**Review by gilgongo — APPROVED** [review]

**Comment by hoffie** [comment]
> @ann0see I have updated changelog and contributors list
> 
> > Thanks for your first PR! @jamulussoftware/designers I think that's something for you.
> 
> Unfortunately, I cannot open that link, it just gives me a 404 man_shrugging

Same for me. I assume this is a Github permission thing. Also same for "maindevelopers" which I have seen mentioned elsewhere. Maybe also related to #932.

**Pull request merged**
