### PR TITLE
Do not show ASIO related warning message if using JACK

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Basically https://github.com/jamulussoftware/jamulus/pull/2168/commits/fd7bfe68af1f25a132da0bb2a9337a09d4dad155 split out as separate commit.

CHANGELOG: Windows: The JACK build now no longer gives an ASIO related warning message on an incompatible state

**Context: Fixes an issue?**
No.

**Does this change need documentation? What needs to be documented and how?**
No. Bug Fix

**Status of this Pull Request**
Not yet tested, just ported

**What is missing until this pull request can be merged?**
Testing and review.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [ ] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [ ] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [ ] I've filled all the content above

### CODE REVIEW

**Review by hoffie — APPROVED** [review]
> Basically https://github.com/jamulussoftware/jamulus/commit/fd7bfe68af1f25a132da0bb2a9337a09d4dad155 split out as separate commit.

That's matches the commit <edit>content</edit> this PR contains. You might have meant another one?

Approving solely on the fact that the previous logic simply does not look correct for non-ASIO builds.

**Comment by ann0see** [comment]
Yes. Basically it's has the same diff (I just copy and pasted it and didn't cherry-pick). Probably that means it's the same commit?

**Comment by ann0see** [comment]
> You might have meant another one?

No. I wanted to get the ( WITH_JACK ) into upstream. 

Just for my own clarification: 
Basically a commit is uniquely determined by the diff?

**Comment by hoffie** [comment]
> > You might have meant another one?
> 
> No. I wanted to get the ( WITH_JACK ) into upstream.

Ok.

> Just for my own clarification: Basically a commit is uniquely determined by the diff?

No, sorry for the confusion. I misread the commit IDs. They are not the same. The commit hash is determined by commit metadata (author, date, message, ...) and commit content (a tree object which describes the full content of the repo).

**Comment by ann0see** [comment]
Ok. Thanks!

Basically it is a split out of https://github.com/jamulussoftware/jamulus/pull/2168

**Review by pljones — APPROVED** [review]

**Pull request merged**
