### PR TITLE
#3050 Save HTML formatting in Server Welcome Message

### PR DESCRIPTION
**Pull request by pljones**
**Short description of changes**

Save the HTML formatting in Server Welcome Message.

**Context: Fixes an issue?**

Fixes: [3050](https://github.com/jamulussoftware/jamulus/issues/3050)

**Does this change need documentation? What needs to be documented and how?**

No.

**Status of this Pull Request**

Tested locally.

**What is missing until this pull request can be merged?**

Could do with @kjcole testing one of the builds.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
@pljones, On the current build, on Debian 10 this error does only occur if I close and reopen twice.

**Comment by kjcole** [comment]
(I didn't test the builds because I didn't know the builds were -- or if I had to build from source, which source?)

**Comment by ann0see** [comment]
> (I didn't test the builds because I didn't know the builds were -- or if I had to build from source, which source?)

I've just killed the build. This should give you access to the artifacts: https://github.com/jamulussoftware/jamulus/actions/runs/4939367648 (scroll down the page and you should be able to see the files)

**Comment by ann0see** [comment]
Yes. My PRs for iOS and macOS

**Comment by pljones** [comment]
> Yes. See my PRs for iOS and macOS

Ah right.

**Comment by ann0see** [comment]
@pljones I think this is changelog worthy.

**Comment by ann0see** [comment]
Yes. I think so

**Pull request merged**
