### PR TITLE
Add iOS Icon

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**

To be able to deploy and test the iOS app on AppStore connect, an icon is needed (https://github.com/jamulussoftware/jamulus/pull/2625#issuecomment-1131915533). I just went the easiest way and created an (ugly version of) the main icon for iOS. This may or may not work with Qt5 builds.
CHANGELOG: iOS: Add icon to iOS app
**Context: Fixes an issue?**

Not directly. However, having an icon is necessary.
**Does this change need documentation? What needs to be documented and how?**

No
**Status of this Pull Request**
Ready for review. Need to check if the Qt5 build fails or not.

**What is missing until this pull request can be merged?**

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want (Qt6 build only, Qt5 will fail or not on GitHub)
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
icon screenshot

**Comment by ann0see** [comment]
@softins @gilgongo could you please also have a look at this one? I'd like to get this in also for iOS support. This makes building with TestFlight easier (as AppStore connect requires an icon)

**Comment by softins** [comment]
I would prefer the icon to match the other platforms. We already have `src/res/io.jamulus.jamulus.png`, `src/res/fronticon.png` and `src/res/win-mainicon.ico`. Putting one of those designs on a white rounded square would look better, I think. That's what "AIM Jamulus" did:
image

If you really need the icon with a blue square background, the white part of the image needs to move down a bit, to be vertically centred.

**Comment by ann0see** [comment]
I would personally prefer to only have the flash in white without the cloud and a blue background. However, I did not succeed to get only the flash out of the image.

**Comment by ann0see** [comment]
The icons are still not perfect, but I'd argue they better now. Also added iOS 18 dark and tinted icons.

**Comment by ann0see** [comment]
iOS Icon

On iOS 17

**Comment by ann0see** [comment]
Simulator Screenshot - iPhone 16 Pro - 2024-10-17 at 23 15 38
Simulator Screenshot - iPhone 16 Pro - 2024-10-17 at 23 15 53

Simulator Screenshot - iPhone 16 Pro - 2024-10-17 at 23 16 00

**Review by softins — APPROVED** [review]
Yes, those icons look fine. I see the CI built successfully with Qt5 (although a few code warnings). I don't know how to load the Unsigned IPA onto my iPad to test it.

**Comment by ann0see** [comment]
As soon as this is merged, I'll create a new TestFlight build with the crash fix.

**Comment by ann0see** [comment]
>  I don't know how to load the Unsigned IPA onto my iPad to test it.

Checkout sideloadly

**Review by softins — APPROVED** [review]
Icon from the new Testflight looks fine, so happy to approve.

**Comment by ann0see** [comment]
@gilgongo @pljones Could you please have a look at this?

**Comment by gilgongo** [comment]
I can't test it natively, but the screens look good to me.

**Comment by ann0see** [comment]
Please merge this PR if you think it's ok then.

**Review by gilgongo — APPROVED** [review]

**Pull request merged**
