### PR TITLE
revert clang-format style changes on 3rd party code

### PR DESCRIPTION
**Pull request by passing**
as discussed in https://github.com/jamulussoftware/jamulus/issues/1702

### CODE REVIEW

**Comment by pljones** [comment]
How did you do the revert?

**Comment by passing** [comment]
I have copied the code from the commit before the style got updated (6d9d94134e64b86b9b539de872ab61c478be515e)

running a diff against that commit shows no changes now on this branch now:
```
$ git diff 6d9d94134e64b86b9b539de872ab61c478be515e windows/nsProcess/
```

in case there is a better/preferred way to do this, please let me know :)

**Comment by pljones** [comment]
> in case there is a better/preferred way to do this, please let me know :)

Lots of ways but what you've done sounds good :)

I'd probably have downloaded the code again - and forgotten to check that had restored things correctly.

**Review by pljones — APPROVED** [review]

**Comment by pljones** [comment]
@softins @hoffie @gilgongo Do we want to take this into 3.8.0 to keep things sane, then (and add this to the folders ignored by clang-format)?

**Comment by softins** [comment]
Sounds sensible to me...

**Review by hoffie — APPROVED** [review]
Revert looks good to me (empty nsprocess/ diff between pre-clang-format and this PR).
I also think this should go into 3.8.0. I'm adding it to the milestone and will merge in the coming days if noone objects.

**Review by ann0see — APPROVED** [review]
Merging soon.

**Pull request merged**
