### PR TITLE
Add Conductor icon

### PR DESCRIPTION
**Pull request by henkdegroot**
**Short description of changes**
Add Conductor icon to instruments

**Context: Fixes an issue?**
Fixes: #1296 

**Does this change need documentation? What needs to be documented and how?**
No. However, Conductor should be translated into other languages.

**Status of this Pull Request**
Complete. Needs reviewers.

**What is missing until this pull request can be merged?**
An independent test would be nice.

## Checklist

- [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
- [x] I tested my code and it does what I want
- [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/master/CONTRIBUTING.md#source-code-consistency) 
- [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
- [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
@henkdegroot Just re-ran the jobs. Hopefully it doesn’t invoke a warning on Windows anymore

**Comment by henkdegroot** [comment]
@ann0see, thank you. I tried to find that option myself but wasn't able to locate it. Guess that is due to rights?
The download is not invoking an warning anymore. It seems is was a false positive as the next day (after Defender updates) it was no longer reported as an issue.

**Comment by henkdegroot** [comment]
I am happy with either....just checked a UK dictionary and they are both listed in that. Though Director is being referenced as being short for Musical Director. I was not sure if Conductor would apply to a leader of a choir, hence my choice of just used Director (also without referencing Band...to allow a wider use). Having that said, the Musical Director text in the dictionary is then referencing the Conductor again.

So happy with any advise a native English speaker can give, as long as we come to an agreement on this and not keep changing it :)

**Comment by pljones** [comment]
I think, on balance, I'd go with Conductor.  Musical Director doesn't tend to come with connotations of live performance of the _music_ - more direction how existing music is used in a final production, even if doing _that_ "live".

**Review by softins — CHANGES_REQUESTED** [review]
I've just successfully built this on my Pi and it runs fine. However, the icon is too large, and causes the channel label box for the conductor channel to be taller than all the others.

Looking at the output of `file src/res/instruments/*.png`, I can see that most of the icons have a height of 27px, one has height of 28px, but the conductor icon has a height of 38px. Please could you resize and update `conductor.png` to have a height of 27 or 28 pixels?

**Review by softins — APPROVED** [review]
Thank you! It looks fine now and works well.

**Comment by henkdegroot** [comment]
I should have considered width **and** height when creation the icon. Thank you for spotting this.

**Comment by pljones** [comment]
If it's been checked in compact skin on Windows, Mac and Linux desktop and looks okay, we're set.  I won't get a chance to try it for a few days.

**Comment by henkdegroot** [comment]
Adding samples here:

Fancy Skin:
condutor-test-fancy

Normal Skin:
condutor-test-normal

Compact Skin:
condutor-test-compact

Two icons in normal skin:
condutor-test-compare

Two icons in compact skin:
condutor-test-compare-compact

I tested in Linux (Ubuntu), macOS Big Sur, Windows 10).

**Comment by softins** [comment]
I just checked all three modes on RaspberryPi OS, with a conductor and another instrument connected, and it looks fine.

**Review by pljones — APPROVED** [review]

**Pull request merged**
