### PR TITLE
Update Mac Legacy from Qt 5.9.9 to 5.15.2

### LINKED ISSUE #3234: Update Qt version for Mac Legacy build
**What is the current behaviour and why should it be changed?**

Currently, the Mac Legacy build uses Qt 5.9.9. It is then able to run on MacOS 10.10 (Yosemite) or later. There are some issues with this:
- The automated build in the CI shows a lot of warnings with this version of Qt, although the build does succeed.
- We want to remove the `.qm` translations files from the repo and have them only built by the `Makefile`, using the `lrelease` config entry in `qmake`. See #2393.
- The `lrelease` functionality in `qmake` is only available in Qt 5.12 or later.

**Describe possible approaches**

The compatibility matrix of Qt versions and minimum MacOS version is as follows:

| Qt version | Minimum MacOS |
|-|-|
| 5.9 | 10.10 (Yosemite) |
| 5.10 | 10.11 (El Capitan) |
| 5.11 | 10.11 |
| 5.12 | 10.12 (Sierra) |
| 5.13 | 10.12 |
| 5.14 | 10.13 (High Sierra) |
| 5.15 | 10.13 |
| 6.0 | 10.14 (Mojave) |
| 6.1 | 10.14 |
| 6.2 | 10.14 |
| 6.3 | 10.14 |
| 6.4 | 10.14 |
| 6.5 | 11 (Big Sur) |
| 6.6 | 11 |

So if we updated the Mac Legacy build to Qt 5.12, we would support 10.12 Sierra onwards. If instead we updated to Qt 5.15, we would support 10.13 (High Sierra) onwards.

The main (non-legacy) MacOS build uses Qt 6.6.1 and therefore only supports MacOS 11 Big Sur or newer. I would expect there still to be demand for supporting at least 10.14 Mojave and 10.15 Catalina for a while yet, and so the Legacy release build is still worthwhile. My own Mac is running Catalina and currently fails to upgrade to Big Sur.

I would favour using Qt 5.15 and therefore dropping support for 10.12 Sierra and older.

**Has this feature been discussed and generally agreed?**

Not yet.

### PR DESCRIPTION
**Pull request by softins**
**Short description of changes**

Updates the CI build process and makefiles for Mac Legacy to use Qt 5.15.2 instead of 5.9.9. This allows other things also to be improved separately, as described in #3234 

CHANGELOG: Update Mac Legacy build to use Qt 5.15.2, now compatible with MacOS 10.13 (High Sierra) or newer.

**Context: Fixes an issue?**

Fixes #3234 

**Does this change need documentation? What needs to be documented and how?**

We would need to document in the release notes and any download page that the minimum supported version of MacOS for the Legacy build would be 10.13 (High Sierra)

**Status of this Pull Request**

Working, but awaiting agreement on using Qt 5.15.2.

**What is missing until this pull request can be merged?**

Just agreement on using Qt 5.15.2

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by softins** [comment]
Reverted to using Qt 5.15.2, as per https://github.com/jamulussoftware/jamulus/issues/3234#issuecomment-1975245901

**Comment by softins** [comment]
I would like to progress this now, because I plan to submit a working PR to replace #2393, and that will be dependent on this one having been merged.

**Review by ann0see — APPROVED** [review]
You know that I have mixed feelings about this but you can argue that people on those devices should have upgraded years ago. 
Going to approve it. But yes, this needs to be explained in the release notes.

**Comment by ann0see** [comment]
We no longer officially link legacy directly on the website anyway as we didn't test it for the last release. So people know it's encouraged not to use it.

**Review by pljones — APPROVED** [review]
Approving because it builds clean.  I've no way to test it.

**Comment by softins** [comment]
Great, I'll do a final smoke test of the artifact and then merge.

**Pull request merged**
