### PR TITLE
Add scrollbars to settings dialog

### LINKED ISSUE #1529: Bad layout of settings dialog in Android
**Describe the bug**

With the code from master, the settings dialog in android is not layout correctly, with the rows appearing *compressed* as the screen is not tall enough.

**To Reproduce**

Install the latest application in android.

**Expected behavior**

Dialog should be layed out properly.

**Screenshots**

Screenshot_20210417-191524

**Operating system**

Android 11 - Google Pixel 3a

**Version of Jamulus**

Built from source at 3df60d6f9faf9bd9fc421187f4e62650abf0b1e0

**Additional context**

### PR DESCRIPTION
**Pull request by j-santander**
Trying to fix #1529

### CODE REVIEW

**Comment by DavidSavinkoff** [comment]
You can get 20% more room! (3 FAT lines worth) without resorting to scroll-bars.
- put Device beside the selector (as Audio Channels and Audio Quality is)
- do the same with Buffer Delay (Buffer is good enough Delay is too much)
- get rid of Measurements (heading)

**Comment by j-santander** [comment]
> 
> 
> You can get 20% more room! (3 FAT lines worth) without resorting to scroll-bars.
> 
>     * put Device beside the selector (as Audio Channels and Audio Quality is)
> 
>     * do the same with Buffer Delay (Buffer is good enough Delay is too much)
> 
>     * get rid of Measurements (heading)

Thanks, I guess that could be possible. I was just adding a minimal change, but more in depth modifications probably should be discussed with @dcorson-ticino-com (I understand was the responsible of the latest redesign of the UI).

**Comment by dcorson-ticino-com** [comment]
Not responsible, but proposing things ;)
Could you try out my NewUI-DCO on your tablet and let me know how it works.
https://github.com/dcorson-ticino-com/jamulus/releases/tag/r3_8_0beta3NewUI

One of the reasons for trying a single window UI was for tablets, but as I don't have one it is all theoretical.

**Comment by pljones** [comment]
I tried a version with the stats/checkbox on the right:
https://github.com/jamulussoftware/jamulus/pull/1542

**Comment by pljones** [comment]
This PR pre-dates the changes to the Settings dialogue.  Can it be closed now?  Does it need redoing from scratch (in which case the PR could be closed until the new version is ready)?

**Comment by dcorson-ticino-com** [comment]
For me it is not necessary, but let's see what the OP says.

**Comment by j-santander** [comment]
Not really sure. I'll try to have a look at the current status of master over the weekend, but please go ahead and close if you think the PR is no longer needed.
Thanks

**Comment by pljones** [comment]
The settings dialog for me, on Windows and Android is fine.  Yes, if you want to, you can make the window _too small_ on Windows.  That could be fixed by setting the minimum width of the various containers correctly (possibly dynamically based on content).

**Comment by ann0see** [comment]
Closing due to inactivity. Probably the GUI issue is even worse on iOS, so definitly something needs to be done. But that's out of scope ;-)

**Pull request closed without merging**
