### PR TITLE
Autobuild: Update macOS SDK

### PR DESCRIPTION
**Pull request by ann0see**
**Short description of changes**
Updates macOS build to all use Xcode 14.2 (macOS 13.1 SDK). Also updates some comments.

CHANGELOG: Build: macOS now uses the 13.1 SDK for better compatibility with modern macOS versions.

**Context: Fixes an issue?**

No

**Does this change need documentation? What needs to be documented and how?**

No

**Status of this Pull Request**

Needs testing on modern macOS. Will do in the coming days.

**What is missing until this pull request can be merged?**

Quick test.

## Checklist

-  [x] I've verified that this Pull Request follows the [general code principles](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#jamulus-projectsource-code-general-principles)
-  [x] I tested my code and it does what I want
-  [x] My code follows the [style guide](https://github.com/jamulussoftware/jamulus/blob/main/CONTRIBUTING.md#source-code-consistency) 
-  [x] I waited some time after this Pull Request was opened and all GitHub checks completed without errors. 
-  [x] I've filled all the content above

### CODE REVIEW

**Comment by ann0see** [comment]
iOS isn't upgradable.

**Comment by pljones** [comment]
I can't check the macOS builds or comment on the workflow, unfortunately.

**Comment by ann0see** [comment]
macOS Ventura 13.4 Client and Server open correctly. Listening works ok. Speaking doesn't work unless I start the app from terminal as it doesn't ask for recording permissions. This might be a bug on my machine only. 

@gilgongo could you please test if this also happens to you?

**Comment by gilgongo** [comment]
I'm on Ventura 13.4.1 (c) - seems to work OK for me (no permissions problem at least, and I can hear and I think transmit OK but I didn't do complete test of that). Settings and connect windows came up in the background for some reason - I had to manually foreground them.

**Comment by pljones** [comment]
> Settings and connect windows came up in the background for some reason - I had to manually foreground them.

Almost certainly more Qt6 issues...

**Comment by ann0see** [comment]
Hmm ok. So the SDK update is probably valid. But what should we do about the buggy Qt?

**Comment by ann0see** [comment]
I think we should be able to upgrade the SDK then.

**Review by pljones — APPROVED** [review]

**Pull request merged**
